import mongoose from "mongoose";

const ref = (model, required = false) => ({ type: mongoose.Schema.Types.ObjectId, ref: model, required, default: required ? undefined : null, index: true });
const money = (value) => Math.round((Number(value || 0) + Number.EPSILON) * 100) / 100;
const qty = (value) => Math.round((Number(value || 0) + Number.EPSILON) * 1e6) / 1e6;

const requestSchema = new mongoose.Schema({
  requestReference: { type: String, required: true, uppercase: true, trim: true }, requestDate: { type: Date, default: Date.now, index: true }, product: ref("Product"), itemName: { type: String, trim: true, default: "" },
  purpose: { type: String, enum: ["manual", "low_stock", "replacement", "general"], default: "manual", index: true }, requiredQuantity: { type: Number, min: 0.000001, required: true, set: qty }, approvedQuantity: { type: Number, min: 0, default: 0, set: qty },
  currentStockSnapshot: { type: Number, default: 0 }, minimumStockSnapshot: { type: Number, default: 0 }, maximumStockSnapshot: { type: Number, default: 0 }, suggestedQuantitySnapshot: { type: Number, default: 0 },
  requester: ref("User", true), department: ref("Department"), reason: { type: String, trim: true, default: "" }, inventoryReference: String, originalPurchase: ref("PurchaseOrder"), purchaseReturn: ref("PurchaseReturn"),
  status: { type: String, enum: ["pending", "approved", "in_analysis", "analyzed", "issued", "completed", "rejected", "cancelled"], default: "pending", index: true }, approver: ref("User"), approvedAt: Date, rejectedBy: ref("User"), rejectedAt: Date, rejectionReason: String, analysis: { type: mongoose.Schema.Types.ObjectId, ref: "PurchaseAnalysis", default: null }, issue: { type: mongoose.Schema.Types.ObjectId, ref: "PurchaseIssue", default: null }, createdBy: ref("User"), updatedBy: ref("User"),
}, { timestamps: true, versionKey: "recordVersion", optimisticConcurrency: true });
requestSchema.index({ requestReference: 1 }, { unique: true }); requestSchema.index({ status: 1, requestDate: -1 });

const offerSchema = new mongoose.Schema({ supplier: ref("Supplier", true), supplierProduct: ref("SupplierProduct"), catalogueUnitPrice: { type: Number, min: 0, default: 0, set: money }, offeredUnitPrice: { type: Number, min: 0, default: 0, set: money }, discountPercent: { type: Number, min: 0, max: 100, default: 0 }, discountThreshold: { type: Number, min: 0, default: 0 }, effectiveUnitCost: { type: Number, min: 0, default: 0, set: money }, previousPurchasePrice: { type: Number, min: 0, default: 0 }, previousPurchaseDate: Date, selected: { type: Boolean, default: false } }, { _id: true });
const analysisSchema = new mongoose.Schema({ analysisReference: { type: String, required: true, uppercase: true, trim: true }, request: { ...ref("PurchaseRequest", true), index: false }, product: ref("Product"), actualDemand: { type: Number, min: 0.000001, required: true, set: qty }, finalQuantity: { type: Number, min: 0.000001, required: true, set: qty }, offers: [offerSchema], selectedSupplier: ref("Supplier"), selectedSupplierProduct: ref("SupplierProduct"), catalogueUnitPrice: { type: Number, min: 0, default: 0, set: money }, purchaseUnitPrice: { type: Number, min: 0, default: 0, set: money }, discountPercent: { type: Number, min: 0, max: 100, default: 0 }, grossAmount: { type: Number, min: 0, default: 0 }, discountAmount: { type: Number, min: 0, default: 0 }, netAmount: { type: Number, min: 0, default: 0 }, analyzer: ref("User"), note: String, status: { type: String, enum: ["pending", "completed", "rejected"], default: "pending", index: true }, completedAt: Date, rejectedBy: ref("User"), rejectionReason: String, issue: { type: mongoose.Schema.Types.ObjectId, ref: "PurchaseIssue", default: null }, createdBy: ref("User"), updatedBy: ref("User") }, { timestamps: true, versionKey: "recordVersion", optimisticConcurrency: true });
analysisSchema.index({ analysisReference: 1 }, { unique: true }); analysisSchema.index({ request: 1 }, { unique: true });
analysisSchema.pre("validate", function(next) { this.grossAmount = money(this.finalQuantity * this.purchaseUnitPrice); this.discountAmount = money(this.grossAmount * this.discountPercent / 100); this.netAmount = money(Math.max(this.grossAmount - this.discountAmount, 0)); next(); });

const issueSchema = new mongoose.Schema({ purchaseReference: { type: String, required: true, uppercase: true, trim: true }, purchaseType: { type: String, enum: ["quick_purchase", "industrial_purchase"], required: true, index: true }, request: { ...ref("PurchaseRequest"), index: false }, analysis: ref("PurchaseAnalysis"), sourceRequestReference: String, product: ref("Product"), newItemName: String, supplier: ref("Supplier", true), supplierProduct: ref("SupplierProduct"), quantity: { type: Number, min: 0.000001, required: true, set: qty }, unitPrice: { type: Number, min: 0, required: true, set: money }, catalogueUnitPrice: { type: Number, min: 0, default: 0 }, discountPercent: { type: Number, min: 0, max: 100, default: 0 }, grossAmount: { type: Number, min: 0, default: 0 }, discountAmount: { type: Number, min: 0, default: 0 }, netAmount: { type: Number, min: 0, default: 0 }, paymentPlan: { type: String, enum: ["full_payment", "full_due", "partial_payment", "after_quality_inspection"], required: true }, paidAmount: { type: Number, min: 0, default: 0 }, dueAmount: { type: Number, min: 0, default: 0 }, paymentDeadline: Date, paymentAccountType: { type: String, enum: ["", "cash", "bank"], default: "" }, cashAccount: ref("CashAccount"), bankAccount: ref("BankAccount"), bankCheckNumber: String, status: { type: String, enum: ["draft", "ready", "completed", "rejected", "cancelled"], default: "draft", index: true }, idempotencyKey: { type: String, trim: true, default: "" }, purchaseOrder: ref("PurchaseOrder"), due: { type: mongoose.Schema.Types.ObjectId, ref: "PurchaseDue", default: null }, qualityInspection: { type: mongoose.Schema.Types.ObjectId, ref: "PurchaseQualityInspection", default: null }, pendingInventory: { type: mongoose.Schema.Types.ObjectId, ref: "PendingInventory", default: null }, completedAt: Date, issuedBy: ref("User"), rejectedBy: ref("User"), rejectionReason: String, createdBy: ref("User"), updatedBy: ref("User") }, { timestamps: true, versionKey: "recordVersion", optimisticConcurrency: true });
issueSchema.index({ purchaseReference: 1 }, { unique: true }); issueSchema.index({ idempotencyKey: 1 }, { unique: true, partialFilterExpression: { idempotencyKey: { $type: "string", $gt: "" } } }); issueSchema.index({ request: 1 }, { unique: true, partialFilterExpression: { request: { $type: "objectId" } } });
issueSchema.pre("validate", function(next) { this.grossAmount = money(this.quantity * this.unitPrice); this.discountAmount = money(this.grossAmount * this.discountPercent / 100); this.netAmount = money(Math.max(this.grossAmount - this.discountAmount, 0)); this.paidAmount = money(this.paidAmount); this.dueAmount = money(Math.max(this.netAmount - this.paidAmount, 0)); next(); });

const paymentSchema = new mongoose.Schema({ paymentReference: { type: String, required: true, uppercase: true, trim: true }, issue: ref("PurchaseIssue", true), due: ref("PurchaseDue"), purchaseOrder: ref("PurchaseOrder"), supplier: ref("Supplier", true), amount: { type: Number, min: 0.01, required: true, set: money }, paymentDate: { type: Date, default: Date.now, index: true }, accountType: { type: String, enum: ["cash", "bank"], required: true }, cashAccount: ref("CashAccount"), bankAccount: ref("BankAccount"), bankCheckNumber: String, journalEntry: ref("JournalEntry"), idempotencyKey: { type: String, required: true }, status: { type: String, enum: ["posted", "reversed"], default: "posted" }, paidBy: ref("User") }, { timestamps: true, versionKey: false });
paymentSchema.index({ paymentReference: 1 }, { unique: true }); paymentSchema.index({ idempotencyKey: 1 }, { unique: true });

const dueSchema = new mongoose.Schema({ dueReference: { type: String, required: true, uppercase: true, trim: true }, issue: ref("PurchaseIssue", true), purchaseOrder: ref("PurchaseOrder"), supplier: ref("Supplier", true), product: ref("Product"), originalNetAmount: { type: Number, min: 0, required: true }, originallyPaidAmount: { type: Number, min: 0, default: 0 }, currentPaidAmount: { type: Number, min: 0, default: 0 }, remainingDue: { type: Number, min: 0, required: true, index: true }, paymentDeadline: { type: Date, default: null, index: true }, paymentPlan: String, qualityStatus: String, status: { type: String, enum: ["outstanding", "partial", "awaiting_inspection", "awaiting_payment", "paid", "locked", "cancelled"], default: "outstanding", index: true }, locked: { type: Boolean, default: false }, lockReason: String, payments: [{ type: mongoose.Schema.Types.ObjectId, ref: "PurchasePayment" }], recordVersion: { type: Number, default: 0 }, createdBy: ref("User"), updatedBy: ref("User") }, { timestamps: true, versionKey: false });
dueSchema.index({ dueReference: 1 }, { unique: true }); dueSchema.index({ supplier: 1, status: 1, paymentDeadline: 1 });

const qualitySchema = new mongoose.Schema({ inspectionReference: { type: String, required: true, uppercase: true, trim: true }, issue: ref("PurchaseIssue", true), purchaseOrder: ref("PurchaseOrder", true), product: ref("Product"), itemName: String, purchasedQuantity: { type: Number, min: 0.000001, required: true }, acceptedQuantity: { type: Number, min: 0, default: 0 }, rejectedQuantity: { type: Number, min: 0, default: 0 }, status: { type: String, enum: ["waiting", "processing", "passed", "partially_accepted", "rejected"], default: "waiting", index: true }, inspector: ref("User"), inspectedAt: Date, note: String, pendingInventory: ref("PendingInventory"), purchaseReturn: ref("PurchaseReturn"), replacementOf: ref("PurchaseReturn") }, { timestamps: true, versionKey: "recordVersion", optimisticConcurrency: true });
qualitySchema.index({ inspectionReference: 1 }, { unique: true }); qualitySchema.index({ issue: 1, replacementOf: 1 }, { unique: true });

const priceSchema = new mongoose.Schema({ analysisReference: { type: String, required: true, uppercase: true, trim: true }, issue: ref("PurchaseIssue"), analysis: ref("PurchaseAnalysis"), product: ref("Product"), supplier: ref("Supplier", true), supplierProduct: ref("SupplierProduct"), purchaseDate: { type: Date, default: Date.now }, catalogueUnitPrice: { type: Number, min: 0, default: 0 }, purchaseUnitPrice: { type: Number, min: 0, default: 0 }, priceDifference: { type: Number, default: 0 }, catalogueDiscount: { type: Number, min: 0, default: 0 }, purchaseDiscount: { type: Number, min: 0, default: 0 }, discountDifference: { type: Number, default: 0 }, status: { type: String, enum: ["pending_review", "accepted_no_update", "catalogue_updated", "rejected"], default: "pending_review", index: true }, reviewedBy: ref("User"), reviewedAt: Date, note: String }, { timestamps: true, versionKey: false });
priceSchema.index({ analysisReference: 1 }, { unique: true });

export const PurchaseRequest = mongoose.model("PurchaseRequest", requestSchema);
export const PurchaseAnalysis = mongoose.model("PurchaseAnalysis", analysisSchema);
export const PurchaseIssue = mongoose.model("PurchaseIssue", issueSchema);
export const PurchasePayment = mongoose.model("PurchasePayment", paymentSchema);
export const PurchaseDue = mongoose.model("PurchaseDue", dueSchema);
export const PurchaseQualityInspection = mongoose.model("PurchaseQualityInspection", qualitySchema);
export const PriceAnalysis = mongoose.model("PriceAnalysis", priceSchema);
