import ManufacturingOrder from "../../models/manufacturing/manufacturingOrder.model.js";
import ManufacturingCost from "../../models/manufacturing/manufacturingCost.model.js";
import MaterialIssue from "../../models/manufacturing/materialIssue.model.js";
import ProductionEntry from "../../models/manufacturing/productionEntry.model.js";
import WorkOrder from "../../models/manufacturing/workOrder.model.js";
import SubcontractOrder from "../../models/manufacturing/subcontractOrder.model.js";
import ScrapEntry from "../../models/manufacturing/scrapEntry.model.js";
import ReworkOrder from "../../models/manufacturing/reworkOrder.model.js";
import StockMovement from "../../models/inventory/stockMovement.model.js";
import Product from "../../models/inventory/product.model.js";
import { nextManufacturingNumber } from "./manufacturingNumbering.service.js";
const money=v=>Math.round(Number(v||0)*100)/100;
export const calculateManufacturingCost = async ({ tenantId, manufacturingOrderId, userId = null, finalize = false }) => {
  const mo = await ManufacturingOrder.findById(manufacturingOrderId).lean();
  if (!mo) throw Object.assign(new Error("Manufacturing order not found."), { statusCode: 404 });
  const issues = await MaterialIssue.find({ manufacturingOrder: mo._id, status: "posted" }).select("stockMovement").lean();
  const moves = await StockMovement.find({ _id: { $in: issues.map(x=>x.stockMovement).filter(Boolean) } }).lean();
  const materialCost = money(moves.flatMap(x=>x.lines||[]).reduce((s,l)=>s+Number(l.appliedValue||0),0));
  const workOrders = await WorkOrder.find({ manufacturingOrder: mo._id }).populate("workCenter", "laborRatePerHour overheadRatePerHour").populate("machine", "hourlyCost").lean();
  const laborCost = money(workOrders.reduce((s,w)=>s+(Number(w.laborMinutes||0)/60)*Number(w.workCenter?.laborRatePerHour||0),0));
  const machineCost = money(workOrders.reduce((s,w)=>s+(Number(w.machineMinutes||0)/60)*Number(w.machine?.hourlyCost||0),0));
  const overheadCost = money(workOrders.reduce((s,w)=>s+(Number(w.laborMinutes||0)/60)*Number(w.workCenter?.overheadRatePerHour||0),0));
  const subcontractCost = money((await SubcontractOrder.find({ manufacturingOrder: mo._id, status: { $in: ["partially_received","received"] } }).select("totalCost").lean()).reduce((s,x)=>s+Number(x.totalCost||0),0));
  const scrapCost = money((await ScrapEntry.find({ manufacturingOrder: mo._id, status: { $ne: "cancelled" } }).select("recoveryValue").lean()).reduce((s,x)=>s+Number(x.recoveryValue||0),0));
  const reworkCost = money((await ReworkOrder.find({ manufacturingOrder: mo._id, status: { $ne: "cancelled" } }).select("actualCost").lean()).reduce((s,x)=>s+Number(x.actualCost||0),0));
  const totalCost = money(materialCost+laborCost+machineCost+overheadCost+subcontractCost+scrapCost+reworkCost);
  const entries = await ProductionEntry.find({ manufacturingOrder: mo._id, status: "posted" }).select("goodQuantity").lean();
  const producedQuantity = entries.reduce((s,x)=>s+Number(x.goodQuantity||0),0);
  const product = await Product.findById(mo.product).select("standardCost").lean();
  const unitCost = producedQuantity>0 ? money(totalCost/producedQuantity) : 0;
  const standardUnitCost = Number(product?.standardCost||0);
  const variance = money(unitCost-standardUnitCost);
  let row = await ManufacturingCost.findOne({ manufacturingOrder: mo._id });
  if (!row) row = new ManufacturingCost({ tenantId, costNumber: await nextManufacturingNumber({ tenantId, key: "cost" }), manufacturingOrder: mo._id });
  Object.assign(row,{ materialCost,laborCost,machineCost,overheadCost,subcontractCost,scrapCost,reworkCost,totalCost,producedQuantity,unitCost,standardUnitCost,variance,status: finalize?"final":"provisional",calculatedAt:new Date(),calculatedBy:userId });
  await row.save();
  await ManufacturingOrder.updateOne({ _id: mo._id }, { $set: { actualCost: totalCost, updatedBy: userId } });
  return row;
};
