"use client"

import { useEffect, useMemo, useState } from "react"
import toast, { Toaster } from "react-hot-toast"
import { FiCheckCircle, FiClock, FiRefreshCcw, FiSave, FiSettings } from "react-icons/fi"

const API_BASE = `${import.meta.env.VITE_API_URL}/api`
const card = "rounded-2xl border border-gray-100 bg-white shadow-[0_14px_35px_-28px_rgba(15,23,42,0.55)]"
const input = "h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm font-semibold text-gray-800 outline-none transition focus:border-indigo-300 focus:ring-4 focus:ring-indigo-500/10"
const button = "inline-flex h-11 items-center justify-center gap-2 rounded-xl px-4 text-sm font-bold transition disabled:opacity-60"
const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
const rule = (prefix) => ({ prefix, digitLength: 6, reset: "fiscal_year", format: "{PREFIX}-{FY}-{NUMBER}" })
const emptyForm = { legalName: "", address: "", taxId: "", vatRegistrationNumber: "", fiscalYearStartMonth: 7, fiscalYearStartDay: 1, defaultFiscalYear: "", currency: "BDT", multiCurrencyEnabled: false, accountingMethod: "accrual", roundingPrecision: 2, defaultCashAccount: "", defaultBankAccount: "", salesAccount: "", purchaseAccount: "", receivableAccount: "", payableAccount: "", payrollExpenseAccount: "", payrollPayableAccount: "", retainedEarningsAccount: "", exchangeGainAccount: "", exchangeLossAccount: "", roundingAccount: "", vatPayableAccount: "", vatReceivableAccount: "", approvalEnabled: false, journalApprovalThreshold: 0, lockDate: "", periodCloseRequireReconciliation: false, defaultTaxScheme: "", taxCalculationMethod: "exclusive", numberingRules: { journal: rule("JV"), invoice: rule("INV"), voucher: rule("PV"), bill: rule("BILL") } }
const tabs = ["General", "Currency", "Numbering", "Default Accounts", "Approval", "Tax", "Period Locking"]
const accountFields = [
  ["defaultCashAccount", "Default Cash", ["asset"]], ["defaultBankAccount", "Default Bank", ["asset"]],
  ["salesAccount", "Sales / Income", ["revenue"]], ["purchaseAccount", "Purchases", ["expense"]],
  ["receivableAccount", "Accounts Receivable Control", ["asset"]], ["payableAccount", "Accounts Payable Control", ["liability"]],
  ["payrollExpenseAccount", "Payroll Expense", ["expense"]], ["payrollPayableAccount", "Payroll Payable", ["liability"]],
  ["retainedEarningsAccount", "Retained Earnings", ["equity"]], ["exchangeGainAccount", "Exchange Gain", ["revenue"]],
  ["exchangeLossAccount", "Exchange Loss", ["expense"]], ["roundingAccount", "Rounding Off", ["expense", "revenue"]],
  ["vatPayableAccount", "VAT Payable", ["liability"]], ["vatReceivableAccount", "VAT Receivable", ["asset"]],
]
function headers() { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) } }
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { credentials: "include", ...options, headers: { ...headers(), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || "Request failed"); return data }
function Field({ label, hint, children }) { return <label className="block"><span className="mb-1.5 block text-sm font-extrabold text-gray-900">{label}</span>{children}{hint ? <span className="mt-1 block text-xs font-semibold text-gray-500">{hint}</span> : null}</label> }
const idOf = (value) => value?._id || value || ""
const dateValue = (value) => value ? new Date(value).toISOString().slice(0, 10) : ""

export default function AccountingSettings() {
  const [form, setForm] = useState(emptyForm); const [accounts, setAccounts] = useState([]); const [fiscalYears, setFiscalYears] = useState([]); const [active, setActive] = useState("General"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [audit, setAudit] = useState(null)
  const load = async () => { setLoading(true); try { const [settingsData, accountData, fiscalData] = await Promise.all([api("/accounting/settings"), api("/accounting/accounts?limit=200"), api("/accounting/fiscal-years")]); const settings = settingsData.settings || {}; setAccounts(accountData.accounts || []); setFiscalYears(fiscalData.fiscalYears || []); setAudit({ user: settings.updatedBy, at: settings.updatedAt }); setForm({ ...emptyForm, ...settings, defaultFiscalYear: idOf(settings.defaultFiscalYear), vatAccount: idOf(settings.vatAccount), lockDate: dateValue(settings.lockDate), numberingRules: { ...emptyForm.numberingRules, ...(settings.numberingRules || {}) }, ...Object.fromEntries(accountFields.map(([key]) => [key, idOf(settings[key])])) }) } catch (error) { toast.error(error.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const readiness = useMemo(() => ({ accounts: accounts.some((a) => !a.isGroup), fiscal: fiscalYears.length > 0 }), [accounts, fiscalYears])
  const setRule = (kind, key, value) => setForm((current) => ({ ...current, numberingRules: { ...current.numberingRules, [kind]: { ...current.numberingRules[kind], [key]: value } } }))
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const data = await api("/accounting/settings", { method: "PUT", body: JSON.stringify({ ...form, fiscalYearStartMonth: Number(form.fiscalYearStartMonth), fiscalYearStartDay: Number(form.fiscalYearStartDay), roundingPrecision: Number(form.roundingPrecision), journalApprovalThreshold: Number(form.journalApprovalThreshold), lockDate: form.lockDate || null, numberingRules: Object.fromEntries(Object.entries(form.numberingRules).map(([key, value]) => [key, { ...value, digitLength: Number(value.digitLength) }])) }) }); setAudit({ user: data.settings?.updatedBy, at: data.settings?.updatedAt }); toast.success("Accounting settings saved") } catch (error) { toast.error(error.message) } finally { setSaving(false) } }
  const accountSelect = (key, label, types) => <Field key={key} label={label}><select className={input} value={form[key]} onChange={(e) => setForm((p) => ({ ...p, [key]: e.target.value }))}><option value="">Not configured</option>{accounts.filter((a) => !a.isGroup && a.isActive !== false && types.includes(a.type)).map((a) => <option key={a._id} value={a._id}>{a.code} — {a.name}</option>)}</select></Field>
  return <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white px-4 py-6 sm:px-6 lg:px-8"><Toaster position="top-right" />
    <div className={`${card} mb-5 p-5`}><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-600 text-white"><FiSettings className="h-6 w-6" /></div><div><p className="text-xs font-black uppercase tracking-[0.18em] text-indigo-600">Accounting Setup</p><h1 className="text-2xl font-black text-gray-950">Accounting Settings</h1><p className="mt-1 text-sm font-semibold text-gray-500">System-wide accounting controls, defaults, numbering, approvals, tax, and locking.</p></div></div><button className={`${button} border border-gray-200 bg-white text-gray-700`} onClick={load} disabled={loading}><FiRefreshCcw className={loading ? "animate-spin" : ""} /> Refresh</button></div>
      <div className="mt-5 flex flex-wrap gap-2 border-t border-gray-100 pt-4"><span className={`rounded-full px-3 py-1.5 text-xs font-black ${readiness.accounts ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}><FiCheckCircle className="mr-1 inline" /> COA {readiness.accounts ? "ready" : "required"}</span><span className={`rounded-full px-3 py-1.5 text-xs font-black ${readiness.fiscal ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}><FiCheckCircle className="mr-1 inline" /> Fiscal year {readiness.fiscal ? "ready" : "required"}</span>{audit?.at ? <span className="ml-auto text-xs font-bold text-gray-500"><FiClock className="mr-1 inline" /> Last modified by {audit.user?.name || audit.user?.email || "system"} on {new Date(audit.at).toLocaleString()}</span> : null}</div></div>
    <form onSubmit={save}><div className={`${card} mb-5 overflow-x-auto p-2`}><div className="flex min-w-max gap-1">{tabs.map((tab) => <button key={tab} type="button" onClick={() => setActive(tab)} className={`rounded-xl px-4 py-2.5 text-sm font-black transition ${active === tab ? "bg-indigo-600 text-white" : "text-gray-600 hover:bg-gray-50"}`}>{tab}</button>)}</div></div>
      <section className={`${card} p-5`}>
        {active === "General" ? <div><h2 className="text-base font-black">Company & accounting basis</h2><div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Legal Company Name"><input className={input} value={form.legalName} onChange={(e) => setForm((p) => ({ ...p, legalName: e.target.value }))} /></Field><Field label="Tax ID"><input className={input} value={form.taxId} onChange={(e) => setForm((p) => ({ ...p, taxId: e.target.value }))} /></Field><Field label="VAT Registration"><input className={input} value={form.vatRegistrationNumber} onChange={(e) => setForm((p) => ({ ...p, vatRegistrationNumber: e.target.value }))} /></Field><Field label="Address"><input className={input} value={form.address} onChange={(e) => setForm((p) => ({ ...p, address: e.target.value }))} /></Field><Field label="Accounting Method"><select className={input} value={form.accountingMethod} onChange={(e) => setForm((p) => ({ ...p, accountingMethod: e.target.value }))}><option value="accrual">Accrual</option><option value="cash">Cash basis</option></select></Field><Field label="Default Fiscal Year"><select className={input} value={form.defaultFiscalYear} onChange={(e) => setForm((p) => ({ ...p, defaultFiscalYear: e.target.value }))}><option value="">Not configured</option>{fiscalYears.map((fy) => <option key={fy._id} value={fy._id}>{fy.name}</option>)}</select></Field><Field label="Fiscal Year Start Month"><select className={input} value={form.fiscalYearStartMonth} onChange={(e) => setForm((p) => ({ ...p, fiscalYearStartMonth: e.target.value }))}>{months.map((m, i) => <option key={m} value={i + 1}>{m}</option>)}</select></Field><Field label="Start Day"><input className={input} type="number" min="1" max="31" value={form.fiscalYearStartDay} onChange={(e) => setForm((p) => ({ ...p, fiscalYearStartDay: e.target.value }))} /></Field></div></div> : null}
        {active === "Currency" ? <div><h2 className="text-base font-black">Currency & rounding</h2><div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Base Currency"><input className={input} value={form.currency} maxLength="3" onChange={(e) => setForm((p) => ({ ...p, currency: e.target.value.toUpperCase() }))} /></Field><Field label="Rounding Precision"><select className={input} value={form.roundingPrecision} onChange={(e) => setForm((p) => ({ ...p, roundingPrecision: e.target.value }))}>{[0, 1, 2, 3, 4].map((n) => <option key={n} value={n}>{n} decimal places</option>)}</select></Field><label className="flex h-11 items-center gap-3 self-end rounded-xl border border-gray-200 px-3 text-sm font-bold"><input type="checkbox" checked={form.multiCurrencyEnabled} onChange={(e) => setForm((p) => ({ ...p, multiCurrencyEnabled: e.target.checked }))} /> Enable multi-currency</label></div></div> : null}
        {active === "Numbering" ? <div><h2 className="text-base font-black">Document numbering rules</h2><p className="mt-1 text-sm font-semibold text-gray-500">Tokens: {"{PREFIX}"}, {"{FY}"}, {"{YYYY}"}, {"{MM}"}, {"{NUMBER}"}</p><div className="mt-4 space-y-3">{Object.entries(form.numberingRules).map(([kind, item]) => <div key={kind} className="grid grid-cols-1 gap-3 rounded-2xl border border-gray-100 p-4 md:grid-cols-[130px_120px_130px_190px_1fr]"><div className="self-center text-sm font-black capitalize">{kind}</div><input className={input} value={item.prefix} onChange={(e) => setRule(kind, "prefix", e.target.value.toUpperCase())} placeholder="Prefix" /><input className={input} type="number" min="3" max="12" value={item.digitLength} onChange={(e) => setRule(kind, "digitLength", e.target.value)} /><select className={input} value={item.reset} onChange={(e) => setRule(kind, "reset", e.target.value)}><option value="fiscal_year">Fiscal year</option><option value="calendar_year">Calendar year</option><option value="monthly">Monthly</option><option value="never">Never</option></select><input className={input} value={item.format} onChange={(e) => setRule(kind, "format", e.target.value)} /></div>)}</div></div> : null}
        {active === "Default Accounts" ? <div><h2 className="text-base font-black">Default control accounts</h2><p className="mt-1 text-sm font-semibold text-gray-500">Only active leaf accounts are selectable.</p><div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">{accountFields.map(([key, label, types]) => accountSelect(key, label, types))}</div></div> : null}
        {active === "Approval" ? <div><h2 className="text-base font-black">Approval controls</h2><div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2"><label className="flex h-11 items-center gap-3 rounded-xl border border-gray-200 px-3 text-sm font-bold"><input type="checkbox" checked={form.approvalEnabled} onChange={(e) => setForm((p) => ({ ...p, approvalEnabled: e.target.checked }))} /> Require accounting approvals</label><Field label="Journal approval threshold"><input className={input} type="number" min="0" step="0.01" disabled={!form.approvalEnabled} value={form.journalApprovalThreshold} onChange={(e) => setForm((p) => ({ ...p, journalApprovalThreshold: e.target.value }))} /></Field></div></div> : null}
        {active === "Tax" ? <div><h2 className="text-base font-black">Tax defaults</h2><div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2"><Field label="Default Tax Scheme"><input className={input} value={form.defaultTaxScheme} onChange={(e) => setForm((p) => ({ ...p, defaultTaxScheme: e.target.value }))} placeholder="Standard VAT" /></Field><Field label="Calculation Method"><select className={input} value={form.taxCalculationMethod} onChange={(e) => setForm((p) => ({ ...p, taxCalculationMethod: e.target.value }))}><option value="exclusive">Tax exclusive</option><option value="inclusive">Tax inclusive</option></select></Field></div></div> : null}
        {active === "Period Locking" ? <div><h2 className="text-base font-black">Global posting lock</h2><div className="mt-4 grid max-w-3xl grid-cols-1 gap-4 md:grid-cols-2"><Field label="Lock Date" hint="No posting or editing is allowed on or before this date."><input className={input} type="date" value={form.lockDate} onChange={(e) => setForm((p) => ({ ...p, lockDate: e.target.value }))} /></Field><label className="flex h-11 items-center gap-3 self-end rounded-xl border border-gray-200 px-3 text-sm font-bold"><input type="checkbox" checked={form.periodCloseRequireReconciliation} onChange={(e) => setForm((p) => ({ ...p, periodCloseRequireReconciliation: e.target.checked }))} /> Require bank reconciliation before period close</label></div></div> : null}
      </section><div className="mt-5 flex justify-end"><button className={`${button} bg-indigo-600 text-white hover:bg-indigo-700`} disabled={saving || loading}><FiSave /> {saving ? "Saving..." : "Save Settings"}</button></div>
    </form>
  </div>
}
