"use client"
/* eslint-disable react/prop-types -- internal report row components receive server-defined accounting shapes */

import { useCallback, useEffect, useMemo, useState } from "react"
import toast, { Toaster } from "react-hot-toast"
import { FiAlertCircle, FiCheckCircle, FiChevronDown, FiChevronRight, FiDownload, FiFileText, FiRefreshCcw, FiSearch, FiSend, FiTrendingUp, FiUsers, FiX } from "react-icons/fi"
import { hasPermission } from "../../Auth/permissions"

const API_BASE = `${import.meta.env.VITE_API_URL}/api`
const card = "rounded-2xl border border-slate-100 bg-white shadow-[0_16px_40px_-30px_rgba(15,23,42,.5)]"
const button = "inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black transition disabled:cursor-not-allowed disabled:opacity-50"
const input = "h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-bold text-slate-800 outline-none focus:border-indigo-300 focus:ring-4 focus:ring-indigo-500/10"
const today = () => new Date().toISOString().slice(0, 10)
const headers = () => { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) } }
const api = async (path, options = {}) => { const response = await fetch(`${API_BASE}${path}`, { credentials: "include", ...options, headers: { ...headers(), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || data.error || "Request failed"); return data }
const loadTreasuryAccounts = async () => {
  let data = await api("/banking/treasury-accounts")
  if (data.unlinkedCount > 0) {
    await api("/banking/treasury-accounts/synchronize", { method: "POST", body: "{}" })
    data = await api("/banking/treasury-accounts")
  }
  return data
}
const amount = (value) => Number(value || 0).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })
const dateText = (value) => value ? new Date(value).toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric" }) : "-"
const userFromStorage = () => { try { const stored = JSON.parse(localStorage.getItem("user") || "null"); return stored?.user || stored } catch { return null } }
const csvCell = (value) => `"${String(value ?? "").replace(/"/g, '""')}"`

function Metric({ label, value, detail, icon, tone = "indigo" }) {
  const tones = { indigo: "bg-indigo-50 text-indigo-700", rose: "bg-rose-50 text-rose-700", emerald: "bg-emerald-50 text-emerald-700", amber: "bg-amber-50 text-amber-700" }
  return <article className={`${card} p-5`}><div className="flex items-start justify-between"><div><p className="text-xs font-black uppercase tracking-[.14em] text-slate-400">{label}</p><p className="mt-2 text-2xl font-black text-slate-950">{value}</p></div><span className={`flex h-11 w-11 items-center justify-center rounded-2xl ${tones[tone]}`}>{icon}</span></div><p className="mt-2 text-xs font-bold text-slate-500">{detail}</p></article>
}

function Modal({ title, subtitle, onClose, children }) {
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/55 p-4 backdrop-blur-sm" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className={`${card} max-h-[92vh] w-full max-w-4xl overflow-auto p-5 sm:p-6`}><div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="text-xl font-black text-slate-950">{title}</h2><p className="mt-1 text-sm font-semibold text-slate-500">{subtitle}</p></div><button className="rounded-xl p-2 text-slate-500 hover:bg-slate-100" onClick={onClose}><FiX /></button></div>{children}</section></div>
}

export default function AccountsReceivable() {
  const user = useMemo(userFromStorage, [])
  const canManage = hasPermission(user, "finance:manage")
  const [data, setData] = useState({ summary: {}, aging: [], agingTotals: {}, topCustomers: [], reconciliation: {} })
  const [drafts, setDrafts] = useState([])
  const [cashAccounts, setCashAccounts] = useState([])
  const [q, setQ] = useState("")
  const [asOf, setAsOf] = useState(today())
  const [from, setFrom] = useState("")
  const [to, setTo] = useState("")
  const [salespersonId, setSalespersonId] = useState("")
  const [expanded, setExpanded] = useState(new Set())
  const [statement, setStatement] = useState(null)
  const [payment, setPayment] = useState(null)
  const [paymentForm, setPaymentForm] = useState({ amount: "", cashAccount: "", paidAt: today(), reference: "", note: "" })
  const [adjustingInvoice, setAdjustingInvoice] = useState(null)
  const [adjustForm, setAdjustForm] = useState({ noteType: "credit_note", amount: "", taxAmount: "0", reason: "", post: true })
  const [loading, setLoading] = useState(false)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const params = new URLSearchParams({ asOf, limit: "75" }); if (q.trim()) params.set("q", q.trim()); if (salespersonId) params.set("salespersonId", salespersonId); if (from) params.set("from", from); if (to) params.set("to", to)
      const requests = [api(`/accounting/receivables?${params}`)]
      if (canManage) requests.push(api("/invoices?limit=100"), loadTreasuryAccounts())
      const [report, draftData, cashData] = await Promise.all(requests)
      setData(report); if (draftData) setDrafts((draftData.items || []).filter((invoice) => !invoice.journalEntry && invoice.status !== "void" && Number(invoice.paidTotal || 0) === 0)); if (cashData) setCashAccounts(cashData.accounts || [])
    } catch (error) { toast.error(error.message) } finally { setLoading(false) }
  }, [asOf, canManage, from, q, salespersonId, to])

  useEffect(() => { const timer = setTimeout(load, 220); return () => clearTimeout(timer) }, [load])
  const salespeople = useMemo(() => { const map = new Map(); for (const party of data.aging || []) for (const invoice of party.invoices || []) { const owner = invoice.salesperson; if (owner?._id) map.set(owner._id, owner) } return [...map.values()] }, [data.aging])
  const toggle = (key) => setExpanded((current) => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next })
  const openStatement = async (party) => { try { setStatement({ loading: true, party }); setStatement(await api(`/accounting/receivables/customers/${party._id}/statement?asOf=${asOf}`)) } catch (error) { setStatement(null); toast.error(error.message) } }
  const postInvoice = async (id) => { try { await api(`/accounting/invoices/${id}/post`, { method: "PATCH", body: "{}" }); toast.success("Invoice posted"); load() } catch (error) { toast.error(error.message) } }
  const openPayment = (invoice) => { setPayment(invoice); setPaymentForm({ amount: invoice.dueTotal, cashAccount: cashAccounts[0]?._id || "", paidAt: today(), reference: "", note: "" }) }
  const recordPayment = async () => { if (!paymentForm.cashAccount) return toast.error("Select a cash or bank account."); const treasury = cashAccounts.find((account) => account._id === paymentForm.cashAccount); try { await api(`/accounting/invoices/${payment._id}/payments`, { method: "POST", body: JSON.stringify({ ...paymentForm, treasuryAccount: paymentForm.cashAccount, treasuryType: treasury?.treasuryType, amount: Number(paymentForm.amount) }) }); toast.success("Receipt posted and applied"); setPayment(null); load() } catch (error) { toast.error(error.message) } }
  const openAdjust = (invoice) => { setAdjustingInvoice(invoice); setAdjustForm({ noteType: "credit_note", amount: String(invoice.dueTotal || invoice.total || ""), taxAmount: "0", reason: "", post: true }) }
  const saveAdjustment = async () => { if (!adjustForm.amount || Number(adjustForm.amount) <= 0) return toast.error("Adjustment amount must be greater than zero."); try { await api("/accounting/adjustment-notes", { method: "POST", body: JSON.stringify({ noteType: adjustForm.noteType, sourceSide: "sales", originalDocumentType: "SalesInvoice", originalDocumentId: adjustingInvoice._id, subtotal: Number(adjustForm.amount), taxAmount: Number(adjustForm.taxAmount || 0), reason: adjustForm.reason, post: adjustForm.post }) }); toast.success("Adjustment note created"); setAdjustingInvoice(null); load() } catch (error) { toast.error(error.message) } }
  const exportCsv = () => { const rows = [["Customer", "Current", "1-30 Days", "31-60 Days", "61-90 Days", "90+ Days", "Total Due"], ...(data.aging || []).map((row) => [row.party?.name, row.current, row.days1to30, row.days31to60, row.days61to90, row.days90plus, row.total])]; const blob = new Blob([rows.map((row) => row.map(csvCell).join(",")).join("\n")], { type: "text/csv" }); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `ar-aging-${asOf}.csv`; link.click(); URL.revokeObjectURL(url) }
  const totals = data.agingTotals || {}

  return <div className="min-h-screen bg-[#f6f7fb] p-4 sm:p-6 lg:p-8"><Toaster position="top-right" />
    <header className={`${card} mb-6 p-5 sm:p-6`}><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Accounting control ledger</p><h1 className="mt-1 text-2xl font-black text-slate-950">Accounts Receivable</h1><p className="mt-1 text-sm font-semibold text-slate-500">Aging, customer statements, collections, and GL reconciliation from posted invoices.</p></div><div className="flex flex-wrap gap-2"><button className={`${button} border border-slate-200 bg-white`} onClick={load}><FiRefreshCcw className={loading ? "animate-spin" : ""} />Refresh</button><button className={`${button} bg-indigo-600 text-white`} onClick={exportCsv}><FiDownload />Export CSV</button></div></div>
      <div className="mt-5 grid gap-3 border-t border-slate-100 pt-4 md:grid-cols-2 xl:grid-cols-5"><label className="relative"><FiSearch className="absolute left-3 top-3.5 text-slate-400" /><input className={`${input} w-full pl-10`} value={q} onChange={(e) => setQ(e.target.value)} placeholder="Customer, invoice, salesperson" /></label><input className={`${input} w-full`} type="date" title="Invoice date from" value={from} onChange={(e) => setFrom(e.target.value)} /><input className={`${input} w-full`} type="date" title="Invoice date to" value={to} onChange={(e) => setTo(e.target.value)} /><input className={`${input} w-full`} type="date" title="Aging as of" value={asOf} onChange={(e) => setAsOf(e.target.value)} /><select className={`${input} w-full`} value={salespersonId} onChange={(e) => setSalespersonId(e.target.value)}><option value="">All salespeople</option>{salespeople.map((person) => <option key={person._id} value={person._id}>{person.name || person.email}</option>)}</select></div></header>

    <div className="mb-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Outstanding" value={amount(data.summary?.outstandingAmount)} detail={`${data.summary?.openInvoiceCount || 0} open posted invoices`} icon={<FiTrendingUp />} /><Metric label="Overdue" value={amount(data.summary?.overdueAmount)} detail={`${data.summary?.overdueCount || 0} overdue invoices`} icon={<FiAlertCircle />} tone="rose" /><Metric label="Customers" value={data.summary?.customerCount || 0} detail="Customers with open balances" icon={<FiUsers />} tone="emerald" /><Metric label="Average days to pay" value={`${data.summary?.dso || 0} days`} detail="Payment-cycle DSO indicator" icon={<FiCheckCircle />} tone="amber" /></div>

    <section className={`${card} mb-6 p-5`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black text-slate-950">Control-account reconciliation</h2><p className="text-sm font-semibold text-slate-500">Open invoices must equal the Accounts Receivable GL balance.</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-black ${data.reconciliation?.reconciled ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{data.reconciliation?.reconciled ? "Reconciled" : `Difference ${amount(data.reconciliation?.difference)}`}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3 text-sm font-bold">Subledger <span className="float-right text-slate-950">{amount(data.reconciliation?.subledgerBalance)}</span></div><div className="rounded-xl bg-slate-50 p-3 text-sm font-bold">GL control account <span className="float-right text-slate-950">{amount(data.reconciliation?.glBalance)}</span></div><div className="rounded-xl bg-slate-50 p-3 text-sm font-bold">Difference <span className="float-right text-slate-950">{amount(data.reconciliation?.difference)}</span></div></div><Trend title="DSO trend" rows={data.dsoTrend} /></section>

    <section className={`${card} overflow-hidden`}><div className="border-b border-slate-100 p-5"><h2 className="font-black text-slate-950">AR Aging Summary</h2><p className="text-sm font-semibold text-slate-500">Click a customer to drill into their open invoices.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-xs font-black uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4 text-left">Customer</th><th className="px-4 py-4 text-right">Current</th><th className="px-4 py-4 text-right">1-30</th><th className="px-4 py-4 text-right">31-60</th><th className="px-4 py-4 text-right">61-90</th><th className="px-4 py-4 text-right">90+</th><th className="px-5 py-4 text-right">Total Due</th><th className="px-5 py-4" /></tr></thead><tbody className="divide-y divide-slate-100">{(data.aging || []).map((row) => { const key = row.party?._id || row.party?.name; return <AgingRows key={key} row={row} open={expanded.has(key)} onToggle={() => toggle(key)} onStatement={() => openStatement(row.party)} onPayment={canManage ? openPayment : null} onAdjust={canManage ? openAdjust : null} /> })}{!(data.aging || []).length ? <tr><td colSpan="8" className="px-5 py-12 text-center font-bold text-slate-400">No open posted receivables for this selection.</td></tr> : null}<tr className="bg-indigo-50 font-black"><td className="px-5 py-4">Total</td>{[totals.current, totals.days1to30, totals.days31to60, totals.days61to90, totals.days90plus, totals.total].map((value, index) => <td key={index} className="px-4 py-4 text-right">{amount(value)}</td>)}<td /></tr></tbody></table></div></section>

    {canManage && drafts.length ? <section className={`${card} mt-6 overflow-hidden`}><div className="border-b border-slate-100 p-5"><h2 className="font-black text-slate-950">Unposted invoices</h2><p className="text-sm font-semibold text-slate-500">Includes safe legacy invoices; posting creates the AR and Sales Revenue journal entry.</p></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><tbody className="divide-y divide-slate-100">{drafts.map((invoice) => <tr key={invoice._id}><td className="px-5 py-4 font-black">{invoice.invoiceNo}</td><td className="px-5 py-4">{invoice.customerId?.companyName || invoice.customerId?.name}</td><td className="px-5 py-4 text-right font-black">{amount(invoice.total)}</td><td className="px-5 py-4 text-right"><button className={`${button} bg-indigo-600 text-white`} onClick={() => postInvoice(invoice._id)}><FiSend />Post invoice</button></td></tr>)}</tbody></table></div></section> : null}

    {statement ? <Modal title={`Statement of Account - ${statement.party?.companyName || statement.party?.name || "Customer"}`} subtitle={`As of ${dateText(statement.asOf || asOf)}`} onClose={() => setStatement(null)}><Statement data={statement} /></Modal> : null}
    {payment ? <Modal title={`Record payment - ${payment.invoiceNo}`} subtitle={`Balance due ${amount(payment.dueTotal)}`} onClose={() => setPayment(null)}><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-black">Amount<input className={`${input} mt-1 w-full`} type="number" min="0.01" max={payment.dueTotal} value={paymentForm.amount} onChange={(e) => setPaymentForm({ ...paymentForm, amount: e.target.value })} /></label><label className="text-sm font-black">Cash / bank account<select className={`${input} mt-1 w-full`} value={paymentForm.cashAccount} onChange={(e) => setPaymentForm({ ...paymentForm, cashAccount: e.target.value })}><option value="">Select account</option>{cashAccounts.map((account) => <option key={`${account.treasuryType}-${account._id}`} value={account._id}>{account.name}{account.detail ? ` - ${account.detail}` : ""}</option>)}</select></label><label className="text-sm font-black">Payment date<input className={`${input} mt-1 w-full`} type="date" value={paymentForm.paidAt} onChange={(e) => setPaymentForm({ ...paymentForm, paidAt: e.target.value })} /></label><label className="text-sm font-black">Reference<input className={`${input} mt-1 w-full`} value={paymentForm.reference} onChange={(e) => setPaymentForm({ ...paymentForm, reference: e.target.value })} /></label></div><button className={`${button} mt-5 bg-indigo-600 text-white`} onClick={recordPayment}>Post receipt and apply</button></Modal> : null}
    {adjustingInvoice ? <Modal title={`Create Adjustment Note - ${adjustingInvoice.invoiceNo}`} subtitle={`Total: ${amount(adjustingInvoice.total)} · Due: ${amount(adjustingInvoice.dueTotal)}`} onClose={() => setAdjustingInvoice(null)}><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-black">Note Type<select className={`${input} mt-1 w-full`} value={adjustForm.noteType} onChange={(e) => setAdjustForm({ ...adjustForm, noteType: e.target.value })}><option value="credit_note">Credit Note (Reduces customer receivable)</option><option value="debit_note">Debit Note (Increases customer receivable)</option></select></label><label className="text-sm font-black">Adjustment Subtotal<input className={`${input} mt-1 w-full`} type="number" min="0.01" step="0.01" value={adjustForm.amount} onChange={(e) => setAdjustForm({ ...adjustForm, amount: e.target.value })} /></label><label className="text-sm font-black">Tax Adjustment<input className={`${input} mt-1 w-full`} type="number" min="0" step="0.01" value={adjustForm.taxAmount} onChange={(e) => setAdjustForm({ ...adjustForm, taxAmount: e.target.value })} /></label><label className="text-sm font-black">Reason / Notes<input className={`${input} mt-1 w-full`} placeholder="Reason for price/discount adjustment" value={adjustForm.reason} onChange={(e) => setAdjustForm({ ...adjustForm, reason: e.target.value })} /></label></div><label className="mt-4 flex items-center gap-2 text-sm font-black"><input type="checkbox" checked={adjustForm.post} onChange={(e) => setAdjustForm({ ...adjustForm, post: e.target.checked })} />Approve and post immediately to General Ledger</label><div className="mt-5 flex justify-end gap-3"><button className={`${button} border border-slate-200 bg-white`} onClick={() => setAdjustingInvoice(null)}>Cancel</button><button className={`${button} bg-indigo-600 text-white`} onClick={saveAdjustment}>Create Adjustment Note</button></div></Modal> : null}
  </div>
}

function AgingRows({ row, open, onToggle, onStatement, onPayment, onAdjust }) {
  return <><tr className="hover:bg-indigo-50/30"><td className="px-5 py-4"><button className="flex items-center gap-2 font-black text-slate-900" onClick={onToggle}>{open ? <FiChevronDown /> : <FiChevronRight />}{row.party?.name}</button></td>{[row.current, row.days1to30, row.days31to60, row.days61to90, row.days90plus, row.total].map((value, index) => <td key={index} className="px-4 py-4 text-right font-bold">{amount(value)}</td>)}<td className="px-5 py-4 text-right"><button className="font-black text-indigo-700 hover:underline" onClick={onStatement}><FiFileText className="mr-1 inline" />Statement</button></td></tr>{open ? row.invoices.map((invoice) => <tr key={invoice._id} className="bg-slate-50/70"><td className="px-5 py-3 pl-12"><span className="font-black text-slate-800">{invoice.invoiceNo}</span><span className="ml-2 text-xs font-bold text-slate-400">{dateText(invoice.issuedAt)} - due {dateText(invoice.dueAt)}</span></td><td colSpan="4" className="px-4 py-3 text-xs font-bold text-slate-500">{invoice.daysOverdue ? `${invoice.daysOverdue} days overdue` : "Current"}</td><td className="px-4 py-3 text-right font-black">{amount(invoice.dueTotal)}</td><td className="px-5 py-3 text-right"><div className="flex items-center justify-end gap-3">{onPayment ? <button className="font-black text-indigo-700 hover:underline" onClick={() => onPayment(invoice)}>Record payment</button> : null}{onAdjust ? <button className="font-black text-slate-600 hover:text-indigo-700 hover:underline" onClick={() => onAdjust(invoice)}>Adjust (CN/DN)</button> : null}</div></td></tr>) : null}</>
}

function Statement({ data }) {
  if (data.loading) return <p className="py-12 text-center font-bold text-slate-500">Loading statement...</p>
  return <><div className="mb-4 flex justify-end"><button className={`${button} border border-slate-200 bg-white`} onClick={() => window.print()}><FiFileText />Print / PDF</button></div><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-xs font-black uppercase text-slate-500"><tr><th className="px-4 py-3 text-left">Date</th><th className="px-4 py-3 text-left">Reference</th><th className="px-4 py-3 text-left">Description</th><th className="px-4 py-3 text-right">Charges</th><th className="px-4 py-3 text-right">Payments</th><th className="px-4 py-3 text-right">Balance</th></tr></thead><tbody className="divide-y divide-slate-100">{(data.transactions || []).map((row, index) => <tr key={`${row.reference}-${index}`}><td className="px-4 py-3">{dateText(row.date)}</td><td className="px-4 py-3 font-black">{row.reference}</td><td className="px-4 py-3">{row.description}</td><td className="px-4 py-3 text-right">{row.charge ? amount(row.charge) : "-"}</td><td className="px-4 py-3 text-right">{row.payment ? amount(row.payment) : "-"}</td><td className="px-4 py-3 text-right font-black">{amount(row.balance)}</td></tr>)}</tbody></table></div><p className="mt-5 text-right text-lg font-black">Balance Due: {amount(data.balanceDue)}</p></>
}

function Trend({ title, rows = [] }) { return rows.length ? <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-4"><span className="mr-1 text-xs font-black uppercase tracking-wider text-slate-400">{title}</span>{rows.map((row) => <span key={row.month} className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-black text-indigo-700">{row.month}: {row.days}d</span>)}</div> : null }
