"use client"

import { useEffect, useState } from "react"
import toast, { Toaster } from "react-hot-toast"
import { FiCalendar, FiLock, FiPlus, FiRefreshCcw, FiUnlock } from "react-icons/fi"

const API_BASE = `${import.meta.env.VITE_API_URL}/api`
const card = "rounded-2xl border border-gray-100 bg-white shadow-[0_14px_35px_-28px_rgba(15,23,42,0.55)]"
const input = "h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm font-semibold text-gray-800 outline-none focus:border-indigo-300 focus:ring-4 focus:ring-indigo-500/10"
const button = "inline-flex items-center justify-center gap-2 rounded-xl px-3 py-2 text-sm font-bold transition disabled:opacity-60"
const today = new Date(); const year = today.getFullYear()
const empty = { name: `${year}-${String(year + 1).slice(-2)}`, startDate: `${year}-07-01`, endDate: `${year + 1}-06-30`, periodFrequency: "monthly", note: "" }
function headers() { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) } }
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { credentials: "include", ...options, headers: { ...headers(), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || "Request failed"); return data }
function Field({ label, children }) { return <label><span className="mb-1.5 block text-sm font-extrabold text-gray-900">{label}</span>{children}</label> }
const dateText = (value) => value ? new Date(value).toLocaleDateString() : "—"

export default function FiscalYearPeriods() {
  const [form, setForm] = useState(empty); const [years, setYears] = useState([]); const [periods, setPeriods] = useState([]); const [selected, setSelected] = useState(""); const [loading, setLoading] = useState(false)
  const load = async (yearId = selected) => { setLoading(true); try { const [fy, ps] = await Promise.all([api("/accounting/fiscal-years"), api(`/accounting/periods?limit=75${yearId ? `&fiscalYearRef=${yearId}` : ""}`)]); setYears(fy.fiscalYears || []); setPeriods(ps.periods || []) } catch (error) { toast.error(error.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const create = async (event) => { event.preventDefault(); try { await api("/accounting/fiscal-years", { method: "POST", body: JSON.stringify(form) }); toast.success("Fiscal year and periods created"); setForm(empty); load() } catch (error) { toast.error(error.message) } }
  const action = async (period, operation) => { try { await api(`/accounting/periods/${encodeURIComponent(period.periodKey)}/${operation}`, { method: "PATCH", body: "{}" }); toast.success(`Period ${operation}ed`); load(selected) } catch (error) { toast.error(error.message) } }
  return <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white px-4 py-6 sm:px-6 lg:px-8"><Toaster position="top-right" />
    <div className={`${card} mb-6 p-5`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-600 text-white"><FiCalendar className="h-6 w-6" /></div><div><p className="text-xs font-black uppercase tracking-[0.18em] text-indigo-600">Accounting Setup</p><h1 className="text-2xl font-black text-gray-950">Fiscal Year / Period</h1><p className="mt-1 text-sm font-semibold text-gray-500">Create accounting years and lock periods to prevent transaction posting.</p></div></div><button className={`${button} border border-gray-200 bg-white`} onClick={() => load(selected)}><FiRefreshCcw className={loading ? "animate-spin" : ""} /> Refresh</button></div></div>
    <form onSubmit={create} className={`${card} mb-6 p-5`}><h2 className="text-base font-black">Create Fiscal Year</h2><div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5"><Field label="Name"><input className={input} value={form.name} onChange={(e) => setForm((p) => ({ ...p, name: e.target.value }))} required /></Field><Field label="Start Date"><input className={input} type="date" value={form.startDate} onChange={(e) => setForm((p) => ({ ...p, startDate: e.target.value }))} required /></Field><Field label="End Date"><input className={input} type="date" value={form.endDate} onChange={(e) => setForm((p) => ({ ...p, endDate: e.target.value }))} required /></Field><Field label="Periods"><select className={input} value={form.periodFrequency} onChange={(e) => setForm((p) => ({ ...p, periodFrequency: e.target.value }))}><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option></select></Field><div className="flex items-end"><button className={`${button} h-11 w-full bg-indigo-600 text-white`}><FiPlus /> Create</button></div></div></form>
    <div className={`${card} overflow-hidden`}><div className="flex flex-col gap-3 border-b border-gray-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black">Accounting Periods</h2><p className="text-sm font-semibold text-gray-500">Locked periods reject journal, payment, and opening-balance postings.</p></div><select className={`${input} sm:w-64`} value={selected} onChange={(e) => { setSelected(e.target.value); load(e.target.value) }}><option value="">All fiscal years</option>{years.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></div><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-100 text-left"><thead className="bg-gray-50 text-xs font-black uppercase tracking-wider text-gray-400"><tr>{["Period", "Fiscal Year", "Start", "End", "Status", "Actions"].map((h) => <th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{periods.map((period) => <tr key={period._id}><td className="px-5 py-4 text-sm font-black">{period.name}</td><td className="px-5 py-4 text-sm font-bold">{period.fiscalYear}</td><td className="px-5 py-4 text-sm font-semibold">{dateText(period.startDate)}</td><td className="px-5 py-4 text-sm font-semibold">{dateText(period.endDate)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-black ${period.status === "open" ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}>{period.status}</span></td><td className="px-5 py-4"><div className="flex gap-2">{period.status === "locked" ? <button className={`${button} border border-gray-200 bg-white`} onClick={() => action(period, "unlock")}><FiUnlock /> Unlock</button> : <button className={`${button} bg-rose-600 text-white`} onClick={() => action(period, "lock")}><FiLock /> Lock</button>}</div></td></tr>)}{!periods.length ? <tr><td colSpan="6" className="px-5 py-14 text-center text-sm font-bold text-gray-500">No accounting periods found.</td></tr> : null}</tbody></table></div></div>
  </div>
}
