"use client"

import { useEffect, useState } from "react"
import toast, { Toaster } from "react-hot-toast"
import { FiCalendar, FiCheckCircle, FiLock, FiPlus, FiRefreshCcw, FiUnlock } from "react-icons/fi"

const API_BASE = `${import.meta.env.VITE_API_URL}/api`
const card = "rounded-2xl border border-gray-100 bg-white shadow-[0_14px_35px_-28px_rgba(15,23,42,0.55)]"
const input = "h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm font-semibold outline-none focus:border-indigo-300 focus:ring-4 focus:ring-indigo-500/10"
const button = "inline-flex items-center justify-center gap-2 rounded-xl px-3 py-2 text-sm font-bold transition disabled:opacity-40"
const year = new Date().getFullYear(); const empty = { name: `FY ${year}-${year + 1}`, startDate: `${year}-07-01`, endDate: `${year + 1}-06-30`, periodFrequency: "monthly", isCurrentYear: true, note: "" }
function headers() { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) } }
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { credentials: "include", ...options, headers: { ...headers(), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || "Request failed"); return data }
function Field({ label, children }) { return <label><span className="mb-1.5 block text-sm font-extrabold">{label}</span>{children}</label> }
const dateText = (value) => value ? new Date(value).toLocaleDateString() : "—"
const badge = (status) => status === "open" ? "bg-emerald-50 text-emerald-700" : status === "locked" ? "bg-rose-50 text-rose-700" : "bg-amber-50 text-amber-700"

export default function FiscalYearPeriods() {
  const [form, setForm] = useState(empty); const [years, setYears] = useState([]); const [periods, setPeriods] = useState([]); const [selected, setSelected] = useState(""); const [loading, setLoading] = useState(false)
  const load = async (id = selected) => { setLoading(true); try { const [fy, ps] = await Promise.all([api("/accounting/fiscal-years"), api(`/accounting/periods?limit=75${id ? `&fiscalYearRef=${id}` : ""}`)]); setYears(fy.fiscalYears || []); setPeriods(ps.periods || []); if (!id && fy.fiscalYears?.length) { const current = fy.fiscalYears.find((item) => item.isCurrentYear) || fy.fiscalYears[0]; setSelected(current._id); const filtered = await api(`/accounting/periods?limit=75&fiscalYearRef=${current._id}`); setPeriods(filtered.periods || []) } } catch (error) { toast.error(error.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const create = async (event) => { event.preventDefault(); try { await api("/accounting/fiscal-years", { method: "POST", body: JSON.stringify(form) }); toast.success("Fiscal year and periods created"); setForm(empty); load() } catch (error) { toast.error(error.message) } }
  const periodAction = async (period, operation) => { try { await api(`/accounting/periods/${encodeURIComponent(period.periodKey)}/${operation}`, { method: "PATCH", body: "{}" }); toast.success(`Period ${operation === "reopen" ? "reopened" : `${operation}ed`}`); load(selected) } catch (error) { toast.error(error.message) } }
  const closeYear = async (fiscalYear) => { if (!window.confirm(`Close ${fiscalYear.name}? This creates the year-end retained earnings entry and cannot be undone from this screen.`)) return; try { const data = await api(`/accounting/fiscal-years/${fiscalYear._id}/close`, { method: "PATCH", body: "{}" }); toast.success(data.openingBalance ? "Fiscal year closed; next-year opening draft generated" : "Fiscal year closed"); load(selected) } catch (error) { toast.error(error.message) } }
  return <div className="min-h-screen bg-gradient-to-b from-gray-50 to-white px-4 py-6 sm:px-6 lg:px-8"><Toaster position="top-right" />
    <div className={`${card} mb-5 p-5`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-indigo-600 text-white"><FiCalendar className="h-6 w-6" /></div><div><p className="text-xs font-black uppercase tracking-[0.18em] text-indigo-600">Step 2 · Accounting Setup</p><h1 className="text-2xl font-black">Fiscal Year / Period</h1><p className="mt-1 text-sm font-semibold text-gray-500">Transactions are accepted only inside open accounting periods.</p></div></div><button className={`${button} border border-gray-200 bg-white`} onClick={() => load(selected)}><FiRefreshCcw className={loading ? "animate-spin" : ""} /> Refresh</button></div></div>
    <form onSubmit={create} className={`${card} mb-5 p-5`}><h2 className="font-black">Create Fiscal Year</h2><div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5"><Field label="Fiscal Year Name"><input className={input} value={form.name} onChange={(e) => setForm((p) => ({ ...p, name: e.target.value }))} required /></Field><Field label="Start Date"><input className={input} type="date" value={form.startDate} onChange={(e) => setForm((p) => ({ ...p, startDate: e.target.value }))} required /></Field><Field label="End Date"><input className={input} type="date" value={form.endDate} onChange={(e) => setForm((p) => ({ ...p, endDate: e.target.value }))} required /></Field><Field label="Period Type"><select className={input} value={form.periodFrequency} onChange={(e) => setForm((p) => ({ ...p, periodFrequency: e.target.value }))}><option value="monthly">Monthly · 12 periods</option><option value="quarterly">Quarterly · 4 periods</option></select></Field><div className="flex flex-col justify-end gap-2"><label className="flex items-center gap-2 text-xs font-bold"><input type="checkbox" checked={form.isCurrentYear} onChange={(e) => setForm((p) => ({ ...p, isCurrentYear: e.target.checked }))} /> Set as current year</label><button className={`${button} h-11 bg-indigo-600 text-white`}><FiPlus /> Create</button></div></div></form>
    <div className={`${card} mb-5 overflow-hidden`}><div className="border-b border-gray-100 p-5"><h2 className="font-black">Fiscal Years</h2><p className="mt-1 text-sm font-semibold text-gray-500">Close a year only after every child period is closed or locked.</p></div><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-100 text-left"><thead className="bg-gray-50 text-xs font-black uppercase tracking-wider text-gray-400"><tr>{["Fiscal Year", "Dates", "Periods", "Status", "Closing Entry", "Actions"].map((h) => <th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{years.map((item) => <tr key={item._id} className={selected === item._id ? "bg-indigo-50/40" : ""}><td className="px-5 py-4"><button className="text-left text-sm font-black text-indigo-700" onClick={() => { setSelected(item._id); load(item._id) }}>{item.name}</button>{item.isCurrentYear ? <span className="ml-2 rounded bg-indigo-100 px-2 py-0.5 text-[10px] font-black text-indigo-700">CURRENT</span> : null}</td><td className="px-5 py-4 text-sm font-semibold">{dateText(item.startDate)} – {dateText(item.endDate)}</td><td className="px-5 py-4 text-sm font-bold capitalize">{item.periodFrequency}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-black ${badge(item.status)}`}>{item.status}</span></td><td className="px-5 py-4 text-sm font-semibold">{item.closingEntry ? "Generated" : "—"}</td><td className="px-5 py-4">{item.status === "open" ? <button className={`${button} bg-gray-900 text-white`} onClick={() => closeYear(item)}><FiCheckCircle /> Close Year</button> : <span className="text-sm font-bold text-gray-500">Closed {dateText(item.closedAt)}</span>}</td></tr>)}</tbody></table></div></div>
    <div className={`${card} overflow-hidden`}><div className="flex items-center justify-between border-b border-gray-100 p-5"><div><h2 className="font-black">Accounting Periods</h2><p className="mt-1 text-sm font-semibold text-gray-500">Close checks for draft journals. Lock is a stronger administrative freeze.</p></div><select className={`${input} w-64`} value={selected} onChange={(e) => { setSelected(e.target.value); load(e.target.value) }}>{years.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></div><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-100 text-left"><thead className="bg-gray-50 text-xs font-black uppercase tracking-wider text-gray-400"><tr>{["Period", "Start", "End", "Status", "Actions"].map((h) => <th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{periods.map((period) => <tr key={period._id}><td className="px-5 py-4 text-sm font-black">{period.name}</td><td className="px-5 py-4 text-sm font-semibold">{dateText(period.startDate)}</td><td className="px-5 py-4 text-sm font-semibold">{dateText(period.endDate)}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-black ${badge(period.status)}`}>{period.status}</span></td><td className="px-5 py-4"><div className="flex gap-2">{period.status === "open" ? <><button className={`${button} bg-amber-500 text-white`} onClick={() => periodAction(period, "close")}><FiCheckCircle /> Close</button><button className={`${button} bg-rose-600 text-white`} onClick={() => periodAction(period, "lock")}><FiLock /> Lock</button></> : null}{period.status === "closed" ? <><button className={`${button} border border-gray-200 bg-white`} onClick={() => periodAction(period, "reopen")}><FiUnlock /> Reopen</button><button className={`${button} bg-rose-600 text-white`} onClick={() => periodAction(period, "lock")}><FiLock /> Lock</button></> : null}{period.status === "locked" ? <button className={`${button} border border-gray-200 bg-white`} onClick={() => periodAction(period, "unlock")}><FiUnlock /> Unlock</button> : null}</div></td></tr>)}{!periods.length ? <tr><td colSpan="5" className="px-5 py-14 text-center text-sm font-bold text-gray-500">Select or create a fiscal year.</td></tr> : null}</tbody></table></div></div>
  </div>
}
