"use client"

import { useEffect, useMemo, useState } from "react"
import toast, { Toaster } from "react-hot-toast"
import { FiAlertTriangle, FiCheckCircle, FiEdit2, FiPlus, FiRefreshCcw, FiSave, FiTrash2, FiX } from "react-icons/fi"
import { hasPermission, PERMISSIONS } from "../../Auth/permissions"

const API_BASE = `${import.meta.env.VITE_API_URL}/api`
const card = "rounded-2xl border border-gray-100 bg-white shadow-[0_14px_35px_-28px_rgba(15,23,42,.55)]"
const btn = "inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black transition disabled:cursor-not-allowed disabled:opacity-50"
const input = "h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm font-bold outline-none focus:border-indigo-300 focus:ring-4 focus:ring-indigo-500/10"
const blank = { name: "", account: "", location: "", custodian: "", currency: "BDT", minimumBalance: "", maximumBalance: "", isActive: true }
function headers() { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) } }
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { credentials: "include", ...options, headers: { ...headers(), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || data.error || "Request failed"); return data }
function money(value, currency = "BDT") { return `${Number(value || 0).toLocaleString("en-US", { maximumFractionDigits: 2 })} ${currency}` }
function Field({ label, children, hint }) { return <label className="block"><span className="mb-1.5 block text-sm font-black text-gray-900">{label}</span>{children}{hint ? <span className="mt-1 block text-xs font-semibold text-gray-500">{hint}</span> : null}</label> }

export default function CashManagement() {
  const user = useMemo(() => { try { const stored = JSON.parse(localStorage.getItem("user") || "null"); return stored?.user || stored } catch { return null } }, [])
  const canManage = hasPermission(user, PERMISSIONS.FINANCE_MANAGE)
  const [rows, setRows] = useState([]); const [ledgers, setLedgers] = useState([]); const [custodians, setCustodians] = useState([]); const [loading, setLoading] = useState(false)
  const [modal, setModal] = useState({ open: false, item: null }); const [form, setForm] = useState(blank); const [verify, setVerify] = useState({ item: null, balance: "", note: "" })
  const load = async () => { setLoading(true); try { const [cash, accounts, people] = await Promise.all([api("/accounting/cash-accounts?type=cash&active=all&limit=200"), api("/accounting/accounts?limit=500"), api("/accounting/cash-custodians")]); setRows(cash.cashAccounts || []); setCustodians(people.users || []); const linked = new Set((cash.cashAccounts || []).map((item) => String(item.account?._id || item.account))); setLedgers((accounts.accounts || []).filter((item) => item.type === "asset" && !item.isGroup && item.isActive !== false && (!linked.has(String(item._id)) || String(modal.item?.account?._id || "") === String(item._id)))) } catch (error) { toast.error(error.message) } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  const open = (item = null) => { setModal({ open: true, item }); setForm(item ? { name: item.name || "", account: item.account?._id || "", location: item.location || "", custodian: item.custodian?._id || "", currency: item.currency || "BDT", minimumBalance: item.minimumBalance || "", maximumBalance: item.maximumBalance || "", isActive: item.isActive !== false } : { ...blank, custodian: user?._id || "" }) }
  const save = async (event) => { event.preventDefault(); try { await api(modal.item ? `/accounting/cash-accounts/${modal.item._id}` : "/accounting/cash-accounts", { method: modal.item ? "PATCH" : "POST", body: JSON.stringify({ ...form, minimumBalance: Number(form.minimumBalance || 0), maximumBalance: Number(form.maximumBalance || 0) }) }); toast.success(modal.item ? "Cash account updated" : "Cash account created"); setModal({ open: false, item: null }); await load() } catch (error) { toast.error(error.message) } }
  const remove = async (item) => { if (!window.confirm(`Delete ${item.name}?`)) return; try { await api(`/accounting/cash-accounts/${item._id}`, { method: "DELETE" }); toast.success("Cash account deleted"); load() } catch (error) { toast.error(error.message) } }
  const confirmCount = async (event) => { event.preventDefault(); try { await api(`/accounting/cash-accounts/${verify.item._id}/reconcile`, { method: "PATCH", body: JSON.stringify({ balance: Number(verify.balance || 0), note: verify.note, reconciledAt: new Date().toISOString() }) }); toast.success("Physical cash count verified"); setVerify({ item: null, balance: "", note: "" }); load() } catch (error) { toast.error(error.message) } }
  return <div className="min-h-screen bg-[#f6f7fb] p-4 sm:p-6 lg:p-8"><Toaster position="top-right" />
    <section className={`${card} mb-6 p-5`}><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Cash &amp; Bank · Master Data</p><h1 className="text-2xl font-black text-gray-950">Cash Management</h1><p className="mt-1 text-sm font-semibold text-gray-500">Physical cash locations connected 1:1 to live General Ledger accounts.</p></div><div className="flex gap-2"><button className={`${btn} border border-gray-200 bg-white`} onClick={load}><FiRefreshCcw className={loading ? "animate-spin" : ""} />Refresh</button>{canManage ? <button className={`${btn} bg-indigo-600 text-white`} onClick={() => open()}><FiPlus />New Cash Account</button> : null}</div></div></section>
    <section className={`${card} overflow-hidden`}><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-100 text-left"><thead className="bg-gray-50 text-xs font-black uppercase text-gray-400"><tr>{["Cash Account", "GL Account", "Location", "Current Balance", "Threshold", "Last Count", "Status", "Actions"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{rows.map((row) => <tr key={row._id} className="hover:bg-gray-50"><td className="px-4 py-3"><p className="text-sm font-black">{row.name}</p><p className="text-xs font-semibold text-gray-500">{row.custodian?.name || "No custodian assigned"}</p></td><td className="px-4 py-3 text-sm font-bold text-indigo-700">{row.account?.code} - {row.account?.name}</td><td className="px-4 py-3 text-sm font-semibold">{row.location || "-"}</td><td className={`px-4 py-3 text-sm font-black ${row.alert ? "text-amber-700" : "text-emerald-700"}`}>{row.alert ? <FiAlertTriangle className="mr-1 inline" /> : null}{money(row.currentBalance, row.currency)}</td><td className="px-4 py-3 text-xs font-bold text-gray-500">Min {money(row.minimumBalance, row.currency)}<br />Max {row.maximumBalance ? money(row.maximumBalance, row.currency) : "No limit"}</td><td className="px-4 py-3 text-xs font-bold">{row.lastReconciledAt ? new Date(row.lastReconciledAt).toLocaleDateString() : "Never"}<br /><span className={row.variance ? "text-rose-600" : "text-gray-400"}>Variance {money(row.variance, row.currency)}</span></td><td className="px-4 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-black ${row.isActive ? "bg-emerald-50 text-emerald-700" : "bg-gray-100 text-gray-500"}`}>{row.isActive ? "Active" : "Inactive"}</span></td><td className="px-4 py-3">{canManage ? <div className="flex gap-2"><button className={`${btn} border border-gray-200 bg-white px-3`} onClick={() => open(row)}><FiEdit2 /></button><button className={`${btn} border border-emerald-200 bg-white px-3 text-emerald-700`} onClick={() => setVerify({ item: row, balance: row.currentBalance, note: "" })} title="Verify physical count"><FiCheckCircle /></button><button className={`${btn} border border-rose-200 bg-white px-3 text-rose-700`} onClick={() => remove(row)}><FiTrash2 /></button></div> : <span className="text-xs font-bold text-gray-400">View only</span>}</td></tr>)}{!rows.length ? <tr><td colSpan={8} className="px-5 py-16 text-center text-sm font-bold text-gray-500">No cash accounts found.</td></tr> : null}</tbody></table></div></section>
      {modal.open ? <div className="fixed inset-0 z-[100] flex items-center justify-center bg-gray-950/55 p-4"><div className="w-full max-w-3xl rounded-2xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><h2 className="text-xl font-black">{modal.item ? "Update" : "Create"} Cash Account</h2><button onClick={() => setModal({ open: false, item: null })}><FiX /></button></div><form onSubmit={save}><div className="grid gap-4 p-5 md:grid-cols-2"><Field label="Cash Account Name"><input className={input} value={form.name} onChange={(e) => setForm((p) => ({ ...p, name: e.target.value }))} required /></Field><Field label="Linked GL Account" hint={modal.item ? "Ledger cannot be replaced here." : "Leave empty to create a dedicated Cash ledger."}><select className={input} value={form.account} disabled={Boolean(modal.item)} onChange={(e) => setForm((p) => ({ ...p, account: e.target.value }))}><option value="">Auto-create dedicated ledger</option>{ledgers.map((item) => <option key={item._id} value={item._id}>{item.code} - {item.name}</option>)}</select></Field><Field label="Location / Branch"><input className={input} value={form.location} onChange={(e) => setForm((p) => ({ ...p, location: e.target.value }))} /></Field><Field label="Custodian"><select className={input} value={form.custodian} onChange={(e) => setForm((p) => ({ ...p, custodian: e.target.value }))}><option value="">Unassigned</option>{custodians.map((person) => <option key={person._id} value={person._id}>{person.name} · {person.email}</option>)}</select></Field><Field label="Currency"><input className={input} maxLength={3} value={form.currency} disabled={Boolean(modal.item)} onChange={(e) => setForm((p) => ({ ...p, currency: e.target.value.toUpperCase() }))} /></Field><Field label="Minimum Balance Alert"><input className={input} type="number" min="0" step=".01" value={form.minimumBalance} onChange={(e) => setForm((p) => ({ ...p, minimumBalance: e.target.value }))} /></Field><Field label="Maximum Balance Alert"><input className={input} type="number" min="0" step=".01" value={form.maximumBalance} onChange={(e) => setForm((p) => ({ ...p, maximumBalance: e.target.value }))} /></Field><label className="flex items-center gap-2 text-sm font-black"><input type="checkbox" checked={form.isActive} onChange={(e) => setForm((p) => ({ ...p, isActive: e.target.checked }))} />Active</label></div><div className="flex justify-end border-t p-5"><button className={`${btn} bg-indigo-600 text-white`}><FiSave />Save Cash Account</button></div></form></div></div> : null}
    {verify.item ? <div className="fixed inset-0 z-[110] flex items-center justify-center bg-gray-950/55 p-4"><form className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl" onSubmit={confirmCount}><h2 className="text-xl font-black">Verify Physical Cash</h2><p className="mt-1 text-sm font-semibold text-gray-500">{verify.item.name} · Book balance {money(verify.item.currentBalance, verify.item.currency)}</p><div className="mt-5 space-y-4"><Field label="Counted Amount"><input className={input} type="number" step=".01" value={verify.balance} onChange={(e) => setVerify((p) => ({ ...p, balance: e.target.value }))} required /></Field><Field label="Verification Note"><textarea className={`${input} h-24 py-3`} value={verify.note} onChange={(e) => setVerify((p) => ({ ...p, note: e.target.value }))} /></Field></div><div className="mt-5 flex justify-end gap-2"><button type="button" className={`${btn} border border-gray-200`} onClick={() => setVerify({ item: null, balance: "", note: "" })}>Cancel</button><button className={`${btn} bg-emerald-600 text-white`}><FiCheckCircle />Verify</button></div></form></div> : null}
  </div>
}
