"use client"
/* eslint-disable react/prop-types -- local voucher fields receive controlled form props */

import { useEffect, useMemo, useState } from "react"
import toast, { Toaster } from "react-hot-toast"
import { FiCheckCircle, FiPlus, FiRefreshCcw, FiRotateCcw, FiSave, FiSend, FiTrash2 } from "react-icons/fi"
import { hasPermission, PERMISSIONS } from "../../Auth/permissions"

const API_BASE = `${import.meta.env.VITE_API_URL}/api`
const card = "rounded-2xl border border-gray-100 bg-white shadow-[0_14px_35px_-28px_rgba(15,23,42,.55)]"
const btn = "inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-black transition disabled:cursor-not-allowed disabled:opacity-50"
const input = "h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm font-bold outline-none focus:border-indigo-300 focus:ring-4 focus:ring-indigo-500/10"
const line = () => ({ account: "", amount: "", description: "", costCenter: "", project: "", taxCode: "" })
const initial = (type) => ({ voucherType: type, date: new Date().toISOString().slice(0, 10), treasuryType: "", treasuryAccount: "", fromType: "", fromAccount: "", toType: "", toAccount: "", amount: "", paymentMode: type === "contra" ? "bank" : "cash", reference: "", narration: "", partyType: type === "payment" ? "supplier" : type === "receipt" ? "customer" : "", partyName: "", chequeNo: "", chequeDate: "", linkedDocuments: [], lines: [line()] })
function headers() { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) } }
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { credentials: "include", ...options, headers: { ...headers(), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || data.error || "Request failed"); return data }
function pretty(value) { return String(value || "-").replace(/_/g, " ").replace(/\b\w/g, (char) => char.toUpperCase()) }
function money(value) { return Number(value || 0).toLocaleString("en-US", { maximumFractionDigits: 2 }) }
function Field({ label, children }) { return <label className="block"><span className="mb-1.5 block text-sm font-black">{label}</span>{children}</label> }

export default function TreasuryVouchers({ defaultType = "payment" }) {
  const user = useMemo(() => { try { const stored = JSON.parse(localStorage.getItem("user") || "null"); return stored?.user || stored } catch { return null } }, [])
  const canManage = hasPermission(user, PERMISSIONS.FINANCE_MANAGE)
  const [type, setType] = useState(defaultType); const [form, setForm] = useState(initial(defaultType)); const [treasury, setTreasury] = useState([]); const [accounts, setAccounts] = useState([]); const [vouchers, setVouchers] = useState([]); const [openDocuments, setOpenDocuments] = useState([]); const [unlinkedBanks, setUnlinkedBanks] = useState([]); const [loading, setLoading] = useState(false)
  const total = useMemo(() => type === "contra" ? Number(form.amount || 0) : form.lines.reduce((sum, item) => sum + Number(item.amount || 0), 0), [form.amount, form.lines, type])
  const selectedTreasury = treasury.find((item) => item._id === form.treasuryAccount && item.treasuryType === form.treasuryType)
  const load = async () => {
    setLoading(true)
    try {
      let [treasuryData, accountData, voucherData, documentData] = await Promise.all([
        api("/banking/treasury-accounts"),
        api("/accounting/accounts?limit=500"),
        api(`/banking/vouchers?voucherType=${type}&limit=100`),
        api(`/banking/open-documents?voucherType=${type}`),
      ])
      if (canManage && treasuryData.unlinkedCount > 0) {
        const synchronized = await api("/banking/treasury-accounts/synchronize", { method: "POST", body: "{}" })
        treasuryData = await api("/banking/treasury-accounts")
        if (synchronized.connected?.length) toast.success(`${synchronized.connected.length} bank account(s) connected to accounting`)
      }
      setTreasury(treasuryData.accounts || [])
      setUnlinkedBanks(treasuryData.unlinkedBankAccounts || [])
      setAccounts((accountData.accounts || []).filter((item) => !item.isGroup && item.isActive !== false))
      setVouchers(voucherData.vouchers || [])
      setOpenDocuments(documentData.documents || [])
    } catch (error) {
      toast.error(error.message)
    } finally {
      setLoading(false)
    }
  }
  // Voucher type is the intentional reload boundary.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { setForm(initial(type)); load() }, [type])
  const updateLine = (index, key, value) => setForm((prev) => ({ ...prev, lines: prev.lines.map((item, i) => i === index ? { ...item, [key]: value } : item) }))
  const toggleDocument = (document) => setForm((prev) => { const exists = prev.linkedDocuments.find((item) => item.documentId === document._id); return { ...prev, linkedDocuments: exists ? prev.linkedDocuments.filter((item) => item.documentId !== document._id) : [...prev.linkedDocuments, { documentType: document.documentType, documentId: document._id, appliedAmount: Math.min(Number(document.due || 0), Math.max(total, 0)) || document.due }] } })
  const updateDocumentAmount = (documentId, value) => setForm((prev) => ({ ...prev, linkedDocuments: prev.linkedDocuments.map((item) => item.documentId === documentId ? { ...item, appliedAmount: value } : item) }))
  const submit = async (event, shouldSubmit = false) => { event.preventDefault(); try { const payload = { ...form, voucherType: type, amount: Number(form.amount || 0), lines: form.lines.map((item) => ({ ...item, amount: Number(item.amount || 0), contactType: form.partyType === "supplier" ? "vendor" : form.partyType })) }; const data = await api("/banking/vouchers", { method: "POST", body: JSON.stringify(payload) }); if (shouldSubmit) await api(`/accounting/journals/${data.voucher._id}/submit`, { method: "PATCH", body: "{}" }); toast.success(shouldSubmit ? "Voucher submitted" : "Voucher saved as draft"); setForm(initial(type)); load() } catch (error) { toast.error(error.message) } }
  const action = async (path, message, body = {}) => { try { await api(path, { method: "PATCH", body: JSON.stringify(body) }); toast.success(message); load() } catch (error) { toast.error(error.message) } }
  const reverse = (voucher) => { const reason = window.prompt("Reason for reversal:"); if (!reason) return; action(`/accounting/journals/${voucher._id}/reverse`, "Reversal voucher posted", { reason, date: new Date().toISOString().slice(0, 10) }) }
  const titles = { payment: ["Payment Voucher", "Money going out from Cash/Bank with an automatically fixed credit side."], receipt: ["Receive Voucher", "Money coming into Cash/Bank with an automatically fixed debit side."], contra: ["Contra Voucher", "Transfer only between the company’s own Cash and Bank accounts."] }
  return <div className="min-h-screen bg-[#f6f7fb] p-4 sm:p-6 lg:p-8"><Toaster position="top-right" />
    <section className={`${card} mb-6 p-5`}><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-indigo-600">Cash &amp; Bank · Shared Voucher Engine</p><h1 className="text-2xl font-black">{titles[type][0]}</h1><p className="mt-1 text-sm font-semibold text-gray-500">{titles[type][1]}</p></div><div className="flex flex-wrap gap-2">{["payment", "receipt", "contra"].map((item) => <button key={item} className={`${btn} ${type === item ? "bg-indigo-600 text-white" : "border border-gray-200 bg-white"}`} onClick={() => setType(item)}>{pretty(item)}</button>)}<button className={`${btn} border border-gray-200 bg-white`} onClick={load}><FiRefreshCcw className={loading ? "animate-spin" : ""} /></button></div></div></section>
    {unlinkedBanks.length ? <div className="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-800">{unlinkedBanks.length} active bank account(s) are not connected to a postable General Ledger account. A finance manager can synchronize them before voucher use.</div> : null}
    {canManage ? <form className={`${card} mb-6`} onSubmit={(event) => submit(event, false)}><div className="grid gap-4 border-b border-gray-100 p-5 md:grid-cols-2 xl:grid-cols-4"><Field label="Voucher Date"><input className={input} type="date" value={form.date} onChange={(e) => setForm((p) => ({ ...p, date: e.target.value }))} required /></Field>{type === "contra" ? <><Field label="Transfer From"><select className={input} value={`${form.fromType}:${form.fromAccount}`} onChange={(e) => { const [fromType, fromAccount] = e.target.value.split(":"); setForm((p) => ({ ...p, fromType, fromAccount })) }} required><option value=":">Select Cash/Bank</option>{treasury.map((item) => <option key={`${item.treasuryType}-${item._id}`} value={`${item.treasuryType}:${item._id}`}>{item.name} · {money(item.currentBalance)} {item.currency}</option>)}</select></Field><Field label="Transfer To"><select className={input} value={`${form.toType}:${form.toAccount}`} onChange={(e) => { const [toType, toAccount] = e.target.value.split(":"); setForm((p) => ({ ...p, toType, toAccount })) }} required><option value=":">Select Cash/Bank</option>{treasury.map((item) => <option key={`${item.treasuryType}-${item._id}`} value={`${item.treasuryType}:${item._id}`}>{item.name}</option>)}</select></Field><Field label="Amount"><input className={input} type="number" min=".01" step=".01" value={form.amount} onChange={(e) => setForm((p) => ({ ...p, amount: e.target.value }))} required /></Field></> : <><Field label={type === "payment" ? "Paid From" : "Received In"}><select className={input} value={`${form.treasuryType}:${form.treasuryAccount}`} onChange={(e) => { const [treasuryType, treasuryAccount] = e.target.value.split(":"); setForm((p) => ({ ...p, treasuryType, treasuryAccount, paymentMode: treasuryType === "cash" ? "cash" : p.paymentMode === "cash" ? "bank" : p.paymentMode })) }} required><option value=":">Select Cash/Bank</option>{treasury.map((item) => <option key={`${item.treasuryType}-${item._id}`} value={`${item.treasuryType}:${item._id}`}>{item.name} · {money(item.currentBalance)} {item.currency}</option>)}</select>{type === "payment" && selectedTreasury && total > selectedTreasury.currentBalance ? <span className="mt-1 block text-xs font-black text-amber-700">Warning: payment exceeds current book balance.</span> : null}</Field><Field label="Party Type"><select className={input} value={form.partyType} onChange={(e) => setForm((p) => ({ ...p, partyType: e.target.value }))}>{(type === "payment" ? ["supplier", "employee", "other"] : ["customer", "other"]).map((item) => <option key={item}>{item}</option>)}</select></Field><Field label={type === "payment" ? "Paid To" : "Received From"}><input className={input} value={form.partyName} onChange={(e) => setForm((p) => ({ ...p, partyName: e.target.value }))} required /></Field></>}
      <Field label="Reference"><input className={input} value={form.reference} onChange={(e) => setForm((p) => ({ ...p, reference: e.target.value }))} /></Field>{type !== "contra" ? <Field label="Payment Mode"><select className={input} value={form.paymentMode} onChange={(e) => setForm((p) => ({ ...p, paymentMode: e.target.value }))}>{["cash", "bank", "cheque", "online", "card", "mobile_banking", "other"].map((item) => <option key={item}>{item}</option>)}</select></Field> : null}{form.paymentMode === "cheque" && type !== "contra" ? <><Field label="Cheque Number"><input className={input} value={form.chequeNo} onChange={(e) => setForm((p) => ({ ...p, chequeNo: e.target.value }))} required /></Field><Field label="Cheque Date"><input className={input} type="date" value={form.chequeDate} onChange={(e) => setForm((p) => ({ ...p, chequeDate: e.target.value }))} /></Field></> : null}<label className="block md:col-span-2 xl:col-span-4"><span className="mb-1.5 block text-sm font-black">Narration</span><textarea className={`${input} h-20 py-3`} value={form.narration} onChange={(e) => setForm((p) => ({ ...p, narration: e.target.value }))} /></label></div>
      {type !== "contra" ? <div className="p-5"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-black">{type === "payment" ? "Debit Allocations" : "Credit Allocations"}</h2><button type="button" className={`${btn} border border-gray-200`} onClick={() => setForm((p) => ({ ...p, lines: [...p.lines, line()] }))}><FiPlus />Add Line</button></div><div className="space-y-3">{form.lines.map((item, index) => <div key={index} className="grid gap-3 rounded-xl border border-gray-100 p-3 md:grid-cols-[1.5fr_.7fr_1fr_auto]"><select className={input} value={item.account} onChange={(e) => updateLine(index, "account", e.target.value)} required><option value="">Select GL Account</option>{accounts.filter((account) => String(account._id) !== String(selectedTreasury?.ledgerAccount?._id || "")).map((account) => <option key={account._id} value={account._id}>{account.code} - {account.name}</option>)}</select><input className={input} type="number" min=".01" step=".01" value={item.amount} onChange={(e) => updateLine(index, "amount", e.target.value)} placeholder="Amount" required /><input className={input} value={item.description} onChange={(e) => updateLine(index, "description", e.target.value)} placeholder="Description" /><button type="button" className={`${btn} border border-rose-200 text-rose-700`} disabled={form.lines.length === 1} onClick={() => setForm((p) => ({ ...p, lines: p.lines.filter((_, i) => i !== index) }))}><FiTrash2 /></button></div>)}</div><div className="mt-4 text-right text-lg font-black">Total: {money(total)} {selectedTreasury?.currency || ""}</div></div> : null}
      {type !== "contra" && openDocuments.length ? <div className="border-t border-gray-100 p-5"><h2 className="text-lg font-black">Settle Against {type === "payment" ? "Supplier Bills" : "Customer Invoices"}</h2><p className="mb-3 text-xs font-semibold text-gray-500">Optional reusable partial/full settlement allocation. Posting updates the selected documents.</p><div className="max-h-64 space-y-2 overflow-y-auto">{openDocuments.filter((document) => !form.partyName || document.partyName.toLowerCase().includes(form.partyName.toLowerCase())).map((document) => { const allocation = form.linkedDocuments.find((item) => item.documentId === document._id); return <div key={document._id} className={`grid items-center gap-3 rounded-xl border p-3 md:grid-cols-[auto_1fr_150px] ${allocation ? "border-indigo-200 bg-indigo-50/50" : "border-gray-100"}`}><input type="checkbox" checked={Boolean(allocation)} onChange={() => toggleDocument(document)} /><div><p className="text-sm font-black">{document.number} · {document.partyName}</p><p className="text-xs font-semibold text-gray-500">Due {money(document.due)} {document.currency} · {document.status}</p></div><input className={input} type="number" min=".01" max={document.due} step=".01" disabled={!allocation} value={allocation?.appliedAmount || ""} onChange={(e) => updateDocumentAmount(document._id, e.target.value)} placeholder="Apply amount" /></div>})}</div></div> : null}
      <div className="flex flex-wrap justify-end gap-2 border-t border-gray-100 p-5"><button className={`${btn} border border-gray-200 bg-white`} type="submit"><FiSave />Save Draft</button><button className={`${btn} bg-indigo-600 text-white`} type="button" onClick={(event) => submit(event, true)}><FiSend />Save &amp; Submit</button></div></form> : <div className="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm font-bold text-amber-800">You have view-only access. Voucher creation and lifecycle actions are hidden.</div>}
    <section className={`${card} overflow-hidden`}><div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-100 text-left"><thead className="bg-gray-50 text-xs font-black uppercase text-gray-400"><tr>{["Voucher", "Date", type === "payment" ? "Paid From" : type === "receipt" ? "Received In" : "Transfer", "Party / Reference", "Amount", "Cheque", "Status", "Actions"].map((h) => <th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-100">{vouchers.map((row) => <tr key={row._id} className="hover:bg-gray-50"><td className="px-4 py-3 text-sm font-black text-indigo-700">{row.entryNo || "Draft"}</td><td className="px-4 py-3 text-sm font-bold">{new Date(row.date).toLocaleDateString()}</td><td className="px-4 py-3 text-sm font-bold">{row.cashAccount?.name || row.bankAccount?.accountName || "Cash/Bank transfer"}</td><td className="px-4 py-3"><p className="text-sm font-bold">{row.partyName || row.memo || "-"}</p><p className="text-xs text-gray-500">{row.reference || "-"}</p></td><td className="px-4 py-3 text-right text-sm font-black">{money(row.totalDebit)} {row.currency}</td><td className="px-4 py-3 text-xs font-bold">{row.chequeNo || "-"}{row.chequeStatus ? <select className="mt-1 block rounded-lg border p-1 text-xs" value={row.chequeStatus} disabled={!canManage} onChange={(e) => action(`/banking/vouchers/${row._id}/cheque-status`, "Cheque status updated", { status: e.target.value })}>{["issued", "presented", "cleared", "bounced"].map((item) => <option key={item}>{item}</option>)}</select> : null}</td><td className="px-4 py-3"><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-black text-indigo-700">{pretty(row.status)}</span></td><td className="px-4 py-3">{canManage ? <div className="flex gap-2">{row.status === "draft" ? <button className={`${btn} bg-indigo-600 px-3 text-white`} onClick={() => action(`/accounting/journals/${row._id}/submit`, "Voucher submitted")}><FiSend /></button> : null}{row.status === "pending_approval" ? <button className={`${btn} bg-emerald-600 px-3 text-white`} onClick={() => action(`/accounting/journals/${row._id}/approve`, "Voucher approved")}><FiCheckCircle /></button> : null}{row.status === "posted" ? <button className={`${btn} border border-rose-200 px-3 text-rose-700`} onClick={() => reverse(row)}><FiRotateCcw /></button> : null}</div> : "-"}</td></tr>)}{!vouchers.length ? <tr><td colSpan={8} className="px-5 py-16 text-center text-sm font-bold text-gray-500">No {type} vouchers found.</td></tr> : null}</tbody></table></div></section>
  </div>
}
