import mongoose from "mongoose";

const workQueueSchema = new mongoose.Schema(
  {
    queueDate: {
      type: Date,
      required: true,
      index: true,
    },

    assignedTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    leadId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Lead",
      default: null,
      index: true,
    },

    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customer",
      default: null,
      index: true,
    },

    dealId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Deal",
      default: null,
      index: true,
    },

    proposalId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Proposal",
      default: null,
      index: true,
    },

    activityId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Activity",
      default: null,
      index: true,
    },

    source: {
      type: String,
      enum: [
        "new_lead",
        "follow_up_due",
        "overdue_follow_up",
        "proposal_follow_up",
        "deal_stuck",
        "manual",
        "automation",
      ],
      required: true,
      index: true,
    },

    title: {
      type: String,
      required: true,
      trim: true,
    },

    description: {
      type: String,
      trim: true,
      default: "",
    },

    recommendedAction: {
      type: String,
      enum: [
        "call",
        "email",
        "whatsapp",
        "meeting",
        "follow_up",
        "send_proposal",
        "create_deal",
        "convert_customer",
        "mark_lost",
        "review",
      ],
      required: true,
      index: true,
    },

    priority: {
      type: String,
      enum: ["low", "normal", "high", "urgent"],
      default: "normal",
      index: true,
    },

    priorityScore: {
      type: Number,
      default: 0,
      min: 0,
      max: 1000,
      index: true,
    },

    status: {
      type: String,
      enum: ["pending", "in_progress", "done", "snoozed", "cancelled"],
      default: "pending",
      index: true,
    },

    dueAt: {
      type: Date,
      default: null,
      index: true,
    },

    startedAt: {
      type: Date,
      default: null,
      index: true,
    },

    doneAt: {
      type: Date,
      default: null,
      index: true,
    },

    snoozedUntil: {
      type: Date,
      default: null,
      index: true,
    },

    result: {
      type: String,
      trim: true,
      default: "",
    },

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
      index: true,
    },

    autoGenerated: {
      type: Boolean,
      default: true,
      index: true,
    },
  },
  { timestamps: true, minimize: true }
);

workQueueSchema.index({ assignedTo: 1, status: 1, priorityScore: -1 });
workQueueSchema.index({ assignedTo: 1, queueDate: 1, status: 1 });
workQueueSchema.index({ leadId: 1, status: 1, createdAt: -1 });
workQueueSchema.index({ source: 1, status: 1, dueAt: 1 });

workQueueSchema.pre("validate", function (next) {
  if (!this.leadId && !this.customerId && !this.dealId && !this.proposalId && !this.activityId) {
    return next(new Error("Work queue item must be connected to a CRM entity"));
  }

  if (this.status === "done" && !this.doneAt) {
    this.doneAt = new Date();
  }

  if (this.status === "in_progress" && !this.startedAt) {
    this.startedAt = new Date();
  }

  next();
});

export default mongoose.model("WorkQueue", workQueueSchema);