import mongoose from "mongoose";

export const PERMISSION_KEYS = [
  "users:view",
  "users:manage",
  "dashboard:view",
  "customers:view",
  "customers:manage",
  "leads:view",
  "leads:manage",
  "deals:view",
  "deals:manage",
  "finance:view",
  "finance:manage",
  "finance:cost-center:view",
  "finance:cost-center:manage",
  "finance:dimension:view",
  "finance:dimension:manage",
  "tasks:view",
  "tasks:manage",
  "reports:view",
  "attendance:view",
  "attendance:manage",
  "payroll:view",
  "payroll:manage",
  "payroll:review",
  "payroll:approve",
  "payroll:disburse",
  "payroll:workflow_configure",
  "tax.view",
  "tax.create",
  "tax.update",
  "tax.delete",
  "tax.assign_employee",
  "tax.report",
  "expenses:view",
  "expenses:manage",
  "expense-setup:view",
  "expense-setup:manage",
  "bank-setup:view",
  "bank-setup:manage",
  "loans:view",
  "loans:manage",
  "leaves:view",
  "leaves:manage",
  "roster:view",
  "roster:manage",
  "employees:view",
  "employees:manage",
  "salary:view",
  "salary:manage",
  "notifications:view",
  "notifications:manage",
  "access-control:view",
  "access-control:manage",
  "workflow:view",
  "profile:view",
  "inventory-product:view",
  "inventory-product:manage",
  "inventory-product:delete",
  "inventory-category:view",
  "inventory-category:manage",
  "inventory-category:delete",
  "inventory-brand:view",
  "inventory-brand:manage",
  "inventory-brand:delete",
  "inventory-unit:view",
  "inventory-unit:manage",
  "inventory-unit:delete",
  "inventory-warehouse:view",
  "inventory-warehouse:manage",
  "inventory-warehouse:delete",
  "inventory-location:view",
  "inventory-location:manage",
  "inventory-location:delete",
  "inventory-stock:view",
  "inventory-stock:manage",
  "inventory-stock:delete",
  "inventory-movement:view",
  "inventory-movement:manage",
  "inventory-movement:post",
  "inventory-movement:reverse",
  "inventory-movement:delete",
  "inventory-adjustment:view",
  "inventory-adjustment:manage",
  "inventory-adjustment:approve",
  "inventory-adjustment:post",
  "inventory-adjustment:reverse",
  "inventory-adjustment:delete",
  "inventory-transfer:view",
  "inventory-transfer:manage",
  "inventory-transfer:approve",
  "inventory-transfer:dispatch",
  "inventory-transfer:receive",
  "inventory-transfer:reverse",
  "inventory-transfer:delete",
  "inventory-report:view",
  "inventory-report:cost-view",
  "inventory-report:export",
  "inventory-reconciliation:view",
  "inventory-integrity:view",
  "inventory-integrity:manage",
  "supplier:view",
  "supplier:manage",
  "supplier:approve",
  "supplier:delete",
  "purchase-order:view",
  "purchase-order:manage",
  "purchase-order:approve",
  "purchase-order:delete",
  "commercial-lc:view",
  "commercial-lc:manage",
  "commercial-lc:approve",
  "commercial-lc:open",
  "commercial-lc:amend",
  "commercial-lc:settle",
  "commercial-lc:close",
  "goods-receipt:view",
  "goods-receipt:manage",
  "goods-receipt:approve",
  "goods-receipt:post",
  "goods-receipt:reverse",
  "goods-receipt:delete",
  "purchase-return:view",
  "purchase-return:manage",
  "purchase-return:approve",
  "purchase-return:post",
  "purchase-return:reverse",
  "purchase-return:delete",
  "purchase-request:view",
  "purchase-request:manage",
  "purchase-request:approve",
  "purchase-analysis:view",
  "purchase-analysis:manage",
  "purchase-issue:view",
  "purchase-issue:manage",
  "purchase-quality:view",
  "purchase-quality:manage",
  "purchase-due:view",
  "purchase-due:pay",
  "price-analysis:view",
  "price-analysis:review",
  "purchase-type:view",
  "purchase-type:manage",
  "sales-quotation:view",
  "sales-quotation:manage",
  "sales-order:view",
  "sales-order:manage",
  "sales-order:approve",
  "sales-delivery:view",
  "sales-delivery:manage",
  "sales-delivery:post",
  "sales-invoice:view",
  "sales-invoice:manage",
  "sales-invoice:post",
  "sales-payment:manage",
  "sales-return:view",
  "sales-return:manage",
  "sales-return:approve",
  "sales-report:view",
  "manufacturing-bom:view",
  "manufacturing-bom:manage",
  "manufacturing-bom:approve",
  "manufacturing-bom:delete",
  "manufacturing-routing:view",
  "manufacturing-routing:manage",
  "manufacturing-routing:delete",
  "manufacturing-work-center:view",
  "manufacturing-work-center:manage",
  "manufacturing-work-center:delete",
  "manufacturing-machine:view",
  "manufacturing-machine:manage",
  "manufacturing-machine:delete",
  "manufacturing-plan:view",
  "manufacturing-plan:manage",
  "manufacturing-plan:approve",
  "manufacturing-plan:delete",
  "manufacturing-mrp:view",
  "manufacturing-mrp:manage",
  "manufacturing-order:view",
  "manufacturing-order:manage",
  "manufacturing-order:release",
  "manufacturing-order:delete",
  "manufacturing-work-order:view",
  "manufacturing-work-order:manage",
  "manufacturing-work-order:execute",
  "manufacturing-material:view",
  "manufacturing-material:manage",
  "manufacturing-material:post",
  "manufacturing-production:view",
  "manufacturing-production:manage",
  "manufacturing-production:post",
  "manufacturing-wip:view",
  "manufacturing-quality:view",
  "manufacturing-quality:manage",
  "manufacturing-quality:approve",
  "manufacturing-scrap:view",
  "manufacturing-scrap:manage",
  "manufacturing-scrap:delete",
  "manufacturing-rework:view",
  "manufacturing-rework:manage",
  "manufacturing-rework:delete",
  "manufacturing-schedule:view",
  "manufacturing-schedule:manage",
  "manufacturing-schedule:delete",
  "manufacturing-maintenance:view",
  "manufacturing-maintenance:manage",
  "manufacturing-subcontract:view",
  "manufacturing-subcontract:manage",
  "manufacturing-subcontract:delete",
  "manufacturing-cost:view",
  "manufacturing-cost:manage",
  "manufacturing-report:view",
  "company:view",
  "company:manage",
  "branch:view",
  "branch:manage",
  "administration-dashboard:view",
  "system-settings:view",
  "system-settings:manage",
];

const permissionGroupSchema = new mongoose.Schema(
  {
    name: { type: String, required: true, trim: true },
    nameLower: { type: String, trim: true, default: "", index: true },
    description: { type: String, trim: true, default: "" },
    permissions: {
      type: [String],
      default: [],
      validate: {
        validator(values) {
          return values.every((value) => PERMISSION_KEYS.includes(value));
        },
        message: "Unknown permission key.",
      },
    },
    isActive: { type: Boolean, default: true, index: true },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  { timestamps: true }
);

permissionGroupSchema.index({ tenantId: 1, nameLower: 1 }, { unique: true });

permissionGroupSchema.pre("save", function (next) {
  if (this.isModified("name")) {
    this.name = String(this.name || "").trim();
    this.nameLower = this.name.toLowerCase();
  }
  if (this.isModified("permissions")) {
    this.permissions = [...new Set(this.permissions || [])];
  }
  next();
});

permissionGroupSchema.pre("findOneAndUpdate", function (next) {
  const update = this.getUpdate() || {};
  const nextName = update.$set?.name ?? update.name;
  const nextPermissions = update.$set?.permissions ?? update.permissions;

  if (nextName !== undefined) {
    const name = String(nextName || "").trim();
    update.$set = {
      ...(update.$set || {}),
      name,
      nameLower: name.toLowerCase(),
    };
    if (update.name !== undefined) delete update.name;
  }

  if (nextPermissions !== undefined) {
    update.$set = {
      ...(update.$set || {}),
      permissions: [...new Set(nextPermissions || [])],
    };
    if (update.permissions !== undefined) delete update.permissions;
  }

  this.setUpdate(update);
  next();
});

export default mongoose.model("PermissionGroup", permissionGroupSchema);
