"use client"
import { FiTool } from "react-icons/fi"
import ManufacturingResourcePage from "./ManufacturingResourcePage"

export default function MaintenanceOrders() {
  return <ManufacturingResourcePage title="Maintenance Orders" subtitle="Track preventive, corrective, breakdown, and inspection work with downtime and cost." endpoint="/manufacturing/maintenance/orders" icon={<FiTool />} viewPermission="manufacturing-maintenance:view" managePermission="manufacturing-maintenance:manage" createLabel="New Maintenance Order" statusOptions={["open", "scheduled", "in_progress", "completed", "cancelled"]}
    columns={[{ key: "maintenanceNumber", label: "Maintenance No." }, { key: "machine", label: "Machine", type: "relation" }, { key: "type", label: "Type" }, { key: "priority", label: "Priority", type: "status" }, { key: "scheduledAt", label: "Scheduled", type: "date" }, { key: "downtimeMinutes", label: "Downtime", render: (row) => `${row.downtimeMinutes || 0} min` }, { key: "laborCost", label: "Labor Cost", type: "money" }, { key: "status", label: "Status", type: "status" }]}
    formFields={[{ name: "maintenanceNumber", label: "Maintenance Number", type: "text" }, { name: "machine", label: "Machine", type: "relation", endpoint: "/manufacturing/machines?limit=100" }, { name: "plan", label: "Maintenance Plan", type: "relation", endpoint: "/manufacturing/maintenance/plans?limit=100", labelKey: "planNumber" }, { name: "type", label: "Type", type: "select", options: ["preventive", "corrective", "breakdown", "inspection"] }, { name: "priority", label: "Priority", type: "select", defaultValue: "normal", options: ["low", "normal", "high", "critical"] }, { name: "scheduledAt", label: "Scheduled At", type: "datetime-local" }, { name: "downtimeMinutes", label: "Downtime Minutes", type: "number", min: 0, defaultValue: 0 }, { name: "laborCost", label: "Labor Cost", type: "number", min: 0, defaultValue: 0 }, { name: "externalCost", label: "External Cost", type: "number", min: 0, defaultValue: 0 }, { name: "findings", label: "Findings", type: "textarea", full: true }, { name: "resolution", label: "Resolution", type: "textarea", full: true }, { name: "status", label: "Status", type: "select", defaultValue: "open", options: ["open", "scheduled", "in_progress", "completed", "cancelled"] }]} />
}
