"use client"
import { FiCalendar } from "react-icons/fi"
import ManufacturingResourcePage from "./ManufacturingResourcePage"

export default function ProductionSchedule() {
  return <ManufacturingResourcePage title="Production Schedule" subtitle="Schedule manufacturing and work orders across work centers and machines with conflict-aware time windows." endpoint="/manufacturing/schedules" icon={<FiCalendar />} viewPermission="manufacturing-schedule:view" managePermission="manufacturing-schedule:manage" deletePermission="manufacturing-schedule:delete" createLabel="New Schedule" statusOptions={["scheduled", "locked", "in_progress", "completed", "cancelled"]}
    columns={[{ key: "scheduleNumber", label: "Schedule No." }, { key: "manufacturingOrder", label: "Manufacturing Order", type: "relation" }, { key: "workCenter", label: "Work Center", type: "relation" }, { key: "machine", label: "Machine", type: "relation" }, { key: "startAt", label: "Start", type: "datetime" }, { key: "endAt", label: "End", type: "datetime" }, { key: "priority", label: "Priority", type: "number" }, { key: "status", label: "Status", type: "status" }]}
    formFields={[{ name: "manufacturingOrder", label: "Manufacturing Order", type: "relation", endpoint: "/manufacturing/orders?limit=100" }, { name: "workOrder", label: "Work Order", type: "relation", endpoint: "/manufacturing/work-orders?limit=100" }, { name: "workCenter", label: "Work Center", type: "relation", endpoint: "/manufacturing/work-centers?limit=100&status=active" }, { name: "machine", label: "Machine", type: "relation", endpoint: "/manufacturing/machines?limit=100" }, { name: "startAt", label: "Start", type: "datetime-local" }, { name: "endAt", label: "End", type: "datetime-local" }, { name: "priority", label: "Priority", type: "number", min: 1, max: 100, defaultValue: 50 }, { name: "status", label: "Status", type: "select", defaultValue: "scheduled", options: ["scheduled", "locked", "in_progress", "completed", "cancelled"] }]} />
}
