"use client"
import { FiRepeat } from "react-icons/fi"
import ManufacturingResourcePage from "./ManufacturingResourcePage"

export default function ReworkOrders() {
  return <ManufacturingResourcePage title="Rework Orders" subtitle="Plan and track rework quantities, routing, reason, planned cost, actual cost, and completion." endpoint="/manufacturing/rework" icon={<FiRepeat />} viewPermission="manufacturing-rework:view" managePermission="manufacturing-rework:manage" deletePermission="manufacturing-rework:delete" createLabel="New Rework Order" statusOptions={["draft", "released", "in_progress", "completed", "cancelled"]}
    columns={[{ key: "reworkNumber", label: "Rework No." }, { key: "manufacturingOrder", label: "Manufacturing Order", type: "relation" }, { key: "product", label: "Product", type: "relation" }, { key: "quantity", label: "Quantity", type: "number" }, { key: "completedQuantity", label: "Completed", type: "number" }, { key: "plannedCost", label: "Planned Cost", type: "money" }, { key: "actualCost", label: "Actual Cost", type: "money" }, { key: "status", label: "Status", type: "status" }]}
    formFields={[{ name: "reworkNumber", label: "Rework Number", type: "text" }, { name: "manufacturingOrder", label: "Manufacturing Order", type: "relation", endpoint: "/manufacturing/orders?limit=100" }, { name: "product", label: "Product", type: "relation", endpoint: "/inventory/products?limit=100&status=active" }, { name: "quantity", label: "Quantity", type: "number", min: 0.000001 }, { name: "routing", label: "Routing", type: "relation", endpoint: "/manufacturing/routing?limit=100&status=active", labelKey: "routeNumber" }, { name: "plannedCost", label: "Planned Cost", type: "number", min: 0, defaultValue: 0 }, { name: "actualCost", label: "Actual Cost", type: "number", min: 0, defaultValue: 0 }, { name: "status", label: "Status", type: "select", defaultValue: "draft", options: ["draft", "released", "in_progress", "completed", "cancelled"] }, { name: "reason", label: "Reason", type: "textarea", full: true }]} />
}
