"use client"
import { FiTrash2 } from "react-icons/fi"
import ManufacturingResourcePage from "./ManufacturingResourcePage"

export default function ScrapWastage() {
  return <ManufacturingResourcePage title="Scrap & Wastage" subtitle="Record production scrap, causes, recoverability, recovery value, and disposition status." endpoint="/manufacturing/scrap" icon={<FiTrash2 />} viewPermission="manufacturing-scrap:view" managePermission="manufacturing-scrap:manage" deletePermission="manufacturing-scrap:delete" createLabel="Record Scrap" statusOptions={["recorded", "approved", "disposed", "recovered", "cancelled"]}
    columns={[{ key: "scrapNumber", label: "Scrap No." }, { key: "manufacturingOrder", label: "Manufacturing Order", type: "relation" }, { key: "product", label: "Product", type: "relation" }, { key: "quantity", label: "Quantity", type: "number" }, { key: "reasonCode", label: "Reason Code" }, { key: "recoverable", label: "Recoverable", type: "boolean" }, { key: "recoveryValue", label: "Recovery Value", type: "money" }, { key: "status", label: "Status", type: "status" }]}
    formFields={[{ name: "scrapNumber", label: "Scrap Number", type: "text" }, { name: "manufacturingOrder", label: "Manufacturing Order", type: "relation", endpoint: "/manufacturing/orders?limit=100" }, { name: "workOrder", label: "Work Order", type: "relation", endpoint: "/manufacturing/work-orders?limit=100" }, { name: "product", label: "Product", type: "relation", endpoint: "/inventory/products?limit=100&status=active" }, { name: "quantity", label: "Quantity", type: "number", min: 0.000001 }, { name: "reasonCode", label: "Reason Code", type: "text" }, { name: "reason", label: "Reason", type: "textarea", full: true }, { name: "recoverable", label: "Recoverable", type: "checkbox" }, { name: "recoveryValue", label: "Recovery Value", type: "number", min: 0, defaultValue: 0 }, { name: "status", label: "Status", type: "select", defaultValue: "recorded", options: ["recorded", "approved", "disposed", "recovered", "cancelled"] }]} />
}
