"use client"
import { FiTruck } from "react-icons/fi"
import ManufacturingResourcePage from "./ManufacturingResourcePage"

export default function Subcontracting() {
  return <ManufacturingResourcePage title="Subcontract Manufacturing" subtitle="Manage outsourced operations, supplier quantities, rates, sent/expected/received dates, and rejection." endpoint="/manufacturing/subcontract" icon={<FiTruck />} viewPermission="manufacturing-subcontract:view" managePermission="manufacturing-subcontract:manage" deletePermission="manufacturing-subcontract:delete" createLabel="New Subcontract Order" statusOptions={["draft", "approved", "sent", "partially_received", "received", "cancelled"]}
    columns={[{ key: "subcontractNumber", label: "Subcontract No." }, { key: "supplier", label: "Supplier", type: "relation" }, { key: "operationName", label: "Operation" }, { key: "quantity", label: "Qty", type: "number" }, { key: "unitRate", label: "Unit Rate", type: "money" }, { key: "totalCost", label: "Total Cost", type: "money" }, { key: "expectedAt", label: "Expected", type: "date" }, { key: "status", label: "Status", type: "status" }]}
    formFields={[{ name: "subcontractNumber", label: "Subcontract Number", type: "text" }, { name: "manufacturingOrder", label: "Manufacturing Order", type: "relation", endpoint: "/manufacturing/orders?limit=100" }, { name: "workOrder", label: "Work Order", type: "relation", endpoint: "/manufacturing/work-orders?limit=100" }, { name: "supplier", label: "Supplier", type: "relation", endpoint: "/suppliers?limit=100&status=approved" }, { name: "operationName", label: "Operation Name", type: "text" }, { name: "quantity", label: "Quantity", type: "number", min: 0.000001 }, { name: "unitRate", label: "Unit Rate", type: "number", min: 0, defaultValue: 0 }, { name: "totalCost", label: "Total Cost", type: "number", min: 0, defaultValue: 0 }, { name: "sentAt", label: "Sent At", type: "date" }, { name: "expectedAt", label: "Expected At", type: "date" }, { name: "receivedAt", label: "Received At", type: "date" }, { name: "receivedQuantity", label: "Received Quantity", type: "number", min: 0, defaultValue: 0 }, { name: "rejectedQuantity", label: "Rejected Quantity", type: "number", min: 0, defaultValue: 0 }, { name: "status", label: "Status", type: "select", defaultValue: "draft", options: ["draft", "approved", "sent", "partially_received", "received", "cancelled"] }, { name: "notes", label: "Notes", type: "textarea", full: true }]} />
}
