import mongoose from "mongoose";

const activitySchema = new mongoose.Schema(
  {
    customerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Customer",
      default: null,
      index: true,
    },

    leadId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Lead",
      default: null,
      index: true,
    },

    dealId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Deal",
      default: null,
      index: true,
    },

    type: {
      type: String,
      enum: ["note", "call", "email", "meeting", "whatsapp", "task_followup"],
      default: "note",
      index: true,
    },

    status: {
      type: String,
      enum: ["pending", "completed", "cancelled"],
      default: "pending",
      index: true,
    },

    priority: {
      type: String,
      enum: ["low", "medium", "high"],
      default: "medium",
      index: true,
    },

    title: { type: String, trim: true, default: "" },
    body: { type: String, trim: true, default: "" },

    scheduledAt: { type: Date, default: null, index: true },
    completedAt: { type: Date, default: null, index: true },

    outcome: { type: String, trim: true, default: "" },
    nextAction: { type: String, trim: true, default: "" },

    /**
     * New quick-action fields
     */
    quickActionKey: {
      type: String,
      enum: [
        "",
        "call_done",
        "whatsapp_sent",
        "email_sent",
        "meeting_scheduled",
        "followup_tomorrow",
        "client_interested",
        "client_not_interested",
        "proposal_requested",
        "proposal_sent",
        "deal_discussed",
      ],
      default: "",
      index: true,
    },

    activityResult: {
      type: String,
      enum: [
        "",
        "positive",
        "neutral",
        "negative",
        "no_response",
        "interested",
        "not_interested",
        "callback_requested",
        "proposal_requested",
      ],
      default: "",
      index: true,
    },

    nextActionDate: {
      type: Date,
      default: null,
      index: true,
    },

    reminderStatus: {
      type: String,
      enum: ["none", "scheduled", "sent", "done", "missed", "cancelled"],
      default: "none",
      index: true,
    },

    autoGenerated: {
      type: Boolean,
      default: false,
      index: true,
    },

    source: {
      type: String,
      enum: ["manual", "quick_action", "automation", "system"],
      default: "manual",
      index: true,
    },

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },

    assignedTo: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
      index: true,
    },
  },
  { timestamps: true, minimize: true }
);

activitySchema.index({ leadId: 1, createdAt: -1 });
activitySchema.index({ customerId: 1, createdAt: -1 });
activitySchema.index({ dealId: 1, createdAt: -1 });
activitySchema.index({ assignedTo: 1, status: 1, scheduledAt: 1 });
activitySchema.index({ assignedTo: 1, reminderStatus: 1, nextActionDate: 1 });
activitySchema.index({ createdBy: 1, createdAt: -1 });
activitySchema.index({ type: 1, status: 1, scheduledAt: 1 });
activitySchema.index({ quickActionKey: 1, createdAt: -1 });

activitySchema.pre("validate", function (next) {
  if (!this.leadId && !this.customerId && !this.dealId) {
    return next(new Error("Activity must be connected to lead, customer, or deal"));
  }

  if (this.status === "completed" && !this.completedAt) {
    this.completedAt = new Date();
  }

  if (this.nextActionDate && this.reminderStatus === "none") {
    this.reminderStatus = "scheduled";
  }

  next();
});

export default mongoose.model("Activity", activitySchema);