/* eslint-disable react/prop-types, react-refresh/only-export-components -- route page exports tested helpers */
"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { createPortal } from "react-dom"
import toast, { Toaster } from "react-hot-toast"
import { FiActivity, FiCheckCircle, FiColumns, FiDatabase, FiDownload, FiEdit2, FiEye, FiPlus, FiSliders, FiX } from "react-icons/fi"
import { hasPermission, PERMISSIONS } from "../../Auth/permissions"
import { InventoryButton, InventoryPageHeader, InventoryPageShell, InventorySearchToolbar } from "./InventoryUI"

const API_BASE = `${import.meta.env.VITE_API_URL}/api`
const PAGE_SIZE = 8
const inputClass = "w-full rounded-xl border border-gray-200 bg-white px-4 py-2.5 text-sm font-semibold text-gray-800 outline-none transition placeholder:text-gray-400 focus:border-indigo-400 focus:ring-4 focus:ring-indigo-500/10 disabled:bg-gray-50 disabled:text-gray-500"
const buttonClass = "inline-flex items-center justify-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold transition focus:outline-none focus-visible:ring-4 focus-visible:ring-indigo-500/15 disabled:cursor-not-allowed disabled:opacity-50"
const emptyForm = { department: "", requester: "", product: "", requestedQuantity: "", purpose: "", requiredDate: "" }

function clean(value) { return String(value ?? "").trim() }
function relationId(value) { return clean(value?._id || value) }
function number(value) { return Number(value || 0).toLocaleString("en-US", { maximumFractionDigits: 6 }) }
function pretty(value) { return clean(value || "—").replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()) }
function dateValue(value) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleDateString("en-CA") }
function todayInput() { return new Date().toISOString().slice(0, 10) }
function getStoredUser() { try { const stored = JSON.parse(localStorage.getItem("user") || "null"); return stored?.user || stored } catch { return null } }
function headers() { const token = localStorage.getItem("token"); return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) } }
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { credentials: "include", ...options, headers: { ...headers(), ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || data.error || "Request failed"); return data }

export function buildStockRequestPayload(form = {}) {
  return { department: clean(form.department), requester: clean(form.requester), product: clean(form.product), requestedQuantity: Number(form.requestedQuantity || 0), notes: clean(form.purpose), requiredDate: clean(form.requiredDate) }
}

export function getStockRequestSummary(rows = [], filteredResults) {
  const pending = rows.filter((row) => clean(row.status).toLowerCase() === "pending")
  const history = rows.filter((row) => clean(row.status).toLowerCase() !== "pending")
  return { totalRecords: history.length, needsAttention: history.filter((row) => ["rejected", "cancelled"].includes(clean(row.status).toLowerCase())).length, totalQuantity: Math.round(history.reduce((sum, row) => sum + Number(row.requestedQuantity || 0), 0) * 1e6) / 1e6, filteredResults: filteredResults ?? history.length, pendingCount: pending.length }
}

export function filterStockRequests(rows = [], filters = {}) {
  const query = clean(filters.query).toLowerCase(), status = clean(filters.status || "all").toLowerCase()
  return rows.filter((row) => {
    if (status !== "all" && clean(row.status).toLowerCase() !== status) return false
    if (!query) return true
    return [row.requestReference, row.requester?.name, row.requester?.employeeId, row.department?.name, row.product?.name, row.product?.sku, row.status, row.notes].some((value) => clean(value).toLowerCase().includes(query))
  })
}

export function paginateStockRequests(rows = [], requestedPage = 1, pageSize = PAGE_SIZE) {
  const totalPages = Math.max(1, Math.ceil(rows.length / pageSize)), page = Math.min(Math.max(1, requestedPage), totalPages), start = (page - 1) * pageSize, end = Math.min(start + pageSize, rows.length)
  return { page, totalPages, start, end, rows: rows.slice(start, end) }
}

async function fetchAllRequests() {
  const items = []; let skip = 0; let total = Infinity
  while (items.length < total) { const data = await api(`/inventory/operations/requests?limit=200&skip=${skip}`), batch = data.items || []; items.push(...batch); total = Number(data.total ?? items.length); if (!batch.length) break; skip += batch.length }
  return items
}

function downloadCsv(rows) {
  const escape = (value) => `"${String(value ?? "").replace(/"/g, '""')}"`
  const data = [["Date", "Request No.", "Requester", "Department", "Product", "Requested Qty", "Available", "Required Date", "Status", "Approver"], ...rows.map((row) => [dateValue(row.requestDate), row.requestReference, row.requester?.name, row.department?.name, row.product?.name, row.requestedQuantity, row.availableQuantity, dateValue(row.requiredDate), pretty(row.status), row.approver?.name])]
  const url = URL.createObjectURL(new Blob([`\uFEFF${data.map((row) => row.map(escape).join(",")).join("\n")}`], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `stock-requests-${todayInput()}.csv`; link.click(); URL.revokeObjectURL(url)
}

function StatusBadge({ status }) {
  const styles = { pending: "border-amber-200 bg-amber-50 text-amber-700", approved: "border-emerald-200 bg-emerald-50 text-emerald-700", issued: "border-blue-200 bg-blue-50 text-blue-700", rejected: "border-rose-200 bg-rose-50 text-rose-700", cancelled: "border-gray-200 bg-gray-100 text-gray-600" }
  return <span className={`inline-flex rounded-lg border px-2 py-1 text-xs font-bold ${styles[clean(status).toLowerCase()] || styles.cancelled}`}>{pretty(status)}</span>
}
function SummaryCard({ label, value, note, icon: Icon, tone }) { const tones = { indigo: "bg-indigo-50 text-indigo-600", amber: "bg-amber-50 text-amber-600", cyan: "bg-cyan-50 text-cyan-600", blue: "bg-blue-50 text-blue-600" }; return <article className="relative rounded-2xl border border-gray-200 bg-white p-4 shadow-[0_12px_30px_-28px_rgba(15,23,42,.55)]"><span className={`absolute right-4 top-4 flex h-10 w-10 items-center justify-center rounded-xl ${tones[tone]}`}><Icon /></span><p className="text-xs font-semibold text-gray-600">{label}</p><p className="mt-2 text-2xl font-black text-gray-950">{value}</p><span className="mt-2 inline-flex rounded-md bg-emerald-50 px-2 py-1 text-[11px] font-semibold text-emerald-700">↗ {note}</span></article> }
function Modal({ open, title, subtitle, onClose, children, footer, width = "max-w-3xl" }) { useEffect(() => { if (!open) return undefined; const before = document.body.style.overflow; document.body.style.overflow = "hidden"; const escape = (event) => event.key === "Escape" && onClose(); window.addEventListener("keydown", escape); return () => { document.body.style.overflow = before; window.removeEventListener("keydown", escape) } }, [onClose, open]); if (!open || typeof document === "undefined") return null; return createPortal(<div className="fixed inset-0 z-[120] overflow-y-auto"><button type="button" aria-label="Close modal" className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm" onClick={onClose} /><div className="relative flex min-h-full items-center justify-center p-4"><div role="dialog" aria-modal="true" className={`relative w-full ${width} overflow-hidden rounded-3xl border border-gray-200 bg-white shadow-2xl`}><header className="flex items-start justify-between border-b border-gray-200 px-5 py-4 sm:px-6"><div><h2 className="text-lg font-black text-gray-950">{title}</h2><p className="mt-1 text-sm font-medium text-gray-500">{subtitle}</p></div><button type="button" className="rounded-xl p-2 text-gray-400 hover:bg-gray-100" onClick={onClose} aria-label="Close"><FiX /></button></header><div className="max-h-[72vh] overflow-y-auto p-5 sm:p-6">{children}</div>{footer ? <footer className="border-t border-gray-200 px-5 py-4 sm:px-6">{footer}</footer> : null}</div></div></div>, document.body) }
function Field({ label, children }) { return <label className="text-sm font-bold text-gray-600">{label}<span className="mt-2 block">{children}</span></label> }
function Detail({ label, value }) { return <div className="rounded-xl border border-gray-100 bg-gray-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-gray-400">{label}</p><div className="mt-2 text-sm font-bold text-gray-800">{value || "—"}</div></div> }
function Pagination({ value, onChange }) { return <footer className="flex flex-col gap-3 border-t border-gray-200 px-4 py-3 text-xs font-medium text-gray-500 sm:flex-row sm:items-center sm:justify-between"><p>Showing {value.end ? value.start + 1 : 0}-{value.end} of {value.total ?? 0} records</p><div className="flex gap-2"><button type="button" className="rounded-xl border border-gray-200 px-3 py-2 font-bold disabled:opacity-40" disabled={value.page <= 1} onClick={() => onChange(value.page - 1)}>Previous</button><span className="flex h-9 min-w-9 items-center justify-center rounded-xl border border-indigo-500 px-3 font-black text-indigo-700">{value.page}</span><button type="button" className="rounded-xl border border-gray-200 px-3 py-2 font-bold disabled:opacity-40" disabled={value.page >= value.totalPages} onClick={() => onChange(value.page + 1)}>Next</button></div></footer> }

export default function StockRequests() {
  const [rows, setRows] = useState([]), [products, setProducts] = useState([]), [employees, setEmployees] = useState([]), [departments, setDepartments] = useState([]), [warehouses, setWarehouses] = useState([]), [locations, setLocations] = useState([])
  const [loading, setLoading] = useState(true), [error, setError] = useState(""), [query, setQuery] = useState(""), [status, setStatus] = useState("all"), [pendingPage, setPendingPage] = useState(1), [historyPage, setHistoryPage] = useState(1)
  const [formOpen, setFormOpen] = useState(false), [form, setForm] = useState(emptyForm), [editing, setEditing] = useState(null), [saving, setSaving] = useState(false), [details, setDetails] = useState(null), [actionKey, setActionKey] = useState("")
  const [issue, setIssue] = useState({ open: false, row: null, warehouse: "", location: "" }), [columnsOpen, setColumnsOpen] = useState(false), [columns, setColumns] = useState({ date: true, requester: true, department: true, available: true, requiredDate: true, approver: true })
  const user = useMemo(getStoredUser, []), canManage = hasPermission(user, PERMISSIONS.INVENTORY_STOCK_MANAGE), canApprove = hasPermission(user, PERMISSIONS.INVENTORY_ADJUSTMENT_APPROVE), canIssue = hasPermission(user, PERMISSIONS.INVENTORY_MOVEMENT_POST)

  const load = useCallback(async () => {
    setLoading(true); setError("")
    try {
      const [requestRows, productData, employeeData, departmentData, warehouseData] = await Promise.all([fetchAllRequests(), api("/inventory/products?status=active&productType=inventory&trackInventory=true&limit=100"), api("/users/employees?active=true&limit=100&sort=newest"), api("/access-control/departments"), api("/inventory/warehouses/options?limit=100")])
      setRows(requestRows); setProducts(productData.products || []); setEmployees(employeeData.employees || []); setDepartments(departmentData.departments || []); setWarehouses(warehouseData.warehouses || [])
    } catch (requestError) { setError(requestError.message || "Unable to load stock requests") } finally { setLoading(false) }
  }, [])
  useEffect(() => { load() }, [load])

  const filtered = useMemo(() => filterStockRequests(rows, { query, status }), [query, rows, status]), pending = useMemo(() => filtered.filter((row) => clean(row.status).toLowerCase() === "pending"), [filtered]), history = useMemo(() => filtered.filter((row) => clean(row.status).toLowerCase() !== "pending"), [filtered])
  const summary = useMemo(() => getStockRequestSummary(rows, history.length), [history.length, rows]), pendingPagination = useMemo(() => ({ ...paginateStockRequests(pending, pendingPage), total: pending.length }), [pending, pendingPage]), historyPagination = useMemo(() => ({ ...paginateStockRequests(history, historyPage), total: history.length }), [history, historyPage])
  useEffect(() => { setPendingPage(1); setHistoryPage(1) }, [query, status])
  useEffect(() => { if (pendingPagination.page !== pendingPage) setPendingPage(pendingPagination.page) }, [pendingPage, pendingPagination.page])
  useEffect(() => { if (historyPagination.page !== historyPage) setHistoryPage(historyPagination.page) }, [historyPage, historyPagination.page])

  const updateForm = (key, value) => setForm((previous) => ({ ...previous, [key]: value })), requesterChanged = (value) => { const employee = employees.find((item) => relationId(item) === value); setForm((previous) => ({ ...previous, requester: value, department: relationId(employee?.department) || previous.department })) }
  const submit = async (event) => { event.preventDefault(); const payload = buildStockRequestPayload(form); if (!payload.department || !payload.requester || !payload.product || payload.requestedQuantity <= 0 || !payload.requiredDate) return toast.error("Complete all required fields"); setSaving(true); try { await api(editing ? `/inventory/operations/requests/${editing._id}` : "/inventory/operations/requests", { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) }); toast.success(editing ? "Stock request updated" : "Stock request created"); setFormOpen(false); setEditing(null); await load() } catch (requestError) { toast.error(requestError.message) } finally { setSaving(false) } }
  const perform = async (row, verb, body = {}) => { if (!row?._id || actionKey) return; setActionKey(`${row._id}:${verb}`); try { await api(`/inventory/operations/requests/${row._id}/${verb}`, { method: "POST", body: JSON.stringify(body) }); toast.success(verb === "approve" ? "Request approved" : verb === "reject" ? "Request rejected" : "Stock issued"); setIssue({ open: false, row: null, warehouse: "", location: "" }); await load() } catch (requestError) { toast.error(requestError.message) } finally { setActionKey("") } }
  const warehouseChanged = async (warehouse) => { setIssue((previous) => ({ ...previous, warehouse, location: "" })); if (!warehouse) return setLocations([]); try { const data = await api(`/inventory/warehouse-locations/options?warehouse=${encodeURIComponent(warehouse)}&limit=200`); setLocations(data.locations || []) } catch { setLocations([]) } }

  return <InventoryPageShell>
    <Toaster position="top-right" toastOptions={{ duration: 2700, style: { borderRadius: "14px", fontWeight: 700 } }} />
    <InventoryPageHeader title="Stock Requests" description="Employees and departments request internal-use items with approval and issue tracking." actions={canManage ? <InventoryButton type="button" variant="primary" icon={FiPlus} onClick={() => { setEditing(null); setForm(emptyForm); setFormOpen(true) }}>Add New</InventoryButton> : null}>
      <InventorySearchToolbar value={query} onChange={setQuery} placeholder="Search stock requests..." ariaLabel="Search stock requests" onClear={() => setQuery("")} filterCount={status === "all" ? 0 : 1} filterControls={<select className={inputClass} value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter request status"><option value="all">All statuses</option>{["pending", "approved", "issued", "rejected", "cancelled"].map((value) => <option key={value} value={value}>{pretty(value)}</option>)}</select>} utilities={<><div className="relative"><InventoryButton type="button" icon={FiColumns} onClick={() => setColumnsOpen((value) => !value)}>Columns</InventoryButton>{columnsOpen ? <div className="absolute right-0 top-12 z-30 w-52 rounded-2xl border border-gray-200 bg-white p-3 shadow-xl">{Object.keys(columns).map((key) => <label key={key} className="flex items-center gap-2 px-2 py-1.5 text-sm font-semibold text-gray-700"><input type="checkbox" checked={columns[key]} onChange={() => setColumns((previous) => ({ ...previous, [key]: !previous[key] }))} />{pretty(key)}</label>)}</div> : null}</div><InventoryButton type="button" icon={FiDownload} onClick={() => downloadCsv(filtered)} disabled={!filtered.length}>Export CSV</InventoryButton></>} />
    </InventoryPageHeader>
    {error ? <div className="mb-4 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div> : null}
    <section className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard label="Total Records" value={summary.totalRecords} note="current records" icon={FiDatabase} tone="indigo" /><SummaryCard label="Needs Attention" value={summary.needsAttention} note={summary.needsAttention ? "review requests" : "all clear"} icon={FiActivity} tone="amber" /><SummaryCard label="Total Quantity / Volume" value={number(summary.totalQuantity)} note="current view basis" icon={FiActivity} tone="cyan" /><SummaryCard label="Filtered Results" value={summary.filteredResults} note="all records" icon={FiSliders} tone="blue" /></section>
    <RequestTable kind="pending" rows={pendingPagination.rows} loading={loading} columns={columns} canManage={canManage} canApprove={canApprove} canIssue={canIssue} actionKey={actionKey} onView={setDetails} onEdit={(row) => { setEditing(row); setForm({ department: relationId(row.department), requester: relationId(row.requester), product: relationId(row.product), requestedQuantity: row.requestedQuantity, purpose: row.notes || "", requiredDate: clean(row.requiredDate).slice(0, 10) }); setFormOpen(true) }} onPerform={perform} onIssue={(row) => setIssue({ open: true, row, warehouse: "", location: "" })} pendingCount={summary.pendingCount} pagination={pendingPagination} setPage={setPendingPage} />
    <RequestTable kind="history" rows={historyPagination.rows} loading={loading} columns={columns} canManage={canManage} canApprove={canApprove} canIssue={canIssue} actionKey={actionKey} onView={setDetails} onEdit={() => {}} onPerform={perform} onIssue={(row) => setIssue({ open: true, row, warehouse: "", location: "" })} pagination={historyPagination} setPage={setHistoryPage} />

    <Modal open={formOpen} onClose={() => { if (!saving) { setFormOpen(false); setEditing(null) } }} title={editing ? "Edit Stock Request" : "Create Stock Request"} subtitle="Fields are designed from the Inventory & Purchase business workflow." footer={<div className="flex justify-end gap-2"><button type="button" className={`${buttonClass} border-gray-200 bg-white text-gray-800`} onClick={() => { setFormOpen(false); setEditing(null) }} disabled={saving}>Cancel</button><button type="submit" form="stock-request-form" className={`${buttonClass} border-indigo-600 bg-indigo-600 text-white`} disabled={saving}>{saving ? "Saving..." : editing ? "Save Changes" : "Create Record"}</button></div>}><form id="stock-request-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2"><Field label="Stock Request No."><input className={inputClass} value={editing?.requestReference || "Auto-generated"} disabled /></Field><Field label="Request Date"><input className={inputClass} value={editing ? dateValue(editing.requestDate) : todayInput()} disabled /></Field><Field label="Department"><select className={inputClass} value={form.department} onChange={(event) => updateForm("department", event.target.value)} required><option value="">Select Department</option>{departments.filter((item) => item.isActive !== false).map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></Field><Field label="Requester"><select className={inputClass} value={form.requester} onChange={(event) => requesterChanged(event.target.value)} required><option value="">Select Requester</option>{employees.map((item) => <option key={item._id} value={item._id}>{item.name}{item.employeeId ? ` (${item.employeeId})` : ""}</option>)}</select></Field><Field label="Product"><select className={inputClass} value={form.product} onChange={(event) => updateForm("product", event.target.value)} required><option value="">Select Product</option>{products.map((item) => <option key={item._id} value={item._id}>{item.name}{item.sku ? ` (${item.sku})` : ""}</option>)}</select></Field><Field label="Requested Quantity"><input className={inputClass} type="number" min="0.000001" step="any" value={form.requestedQuantity} onChange={(event) => updateForm("requestedQuantity", event.target.value)} placeholder="Enter requested quantity" required /></Field><label className="text-sm font-bold text-gray-600 sm:col-span-2">Purpose<textarea className={`${inputClass} mt-2 min-h-24 resize-y`} value={form.purpose} onChange={(event) => updateForm("purpose", event.target.value)} placeholder="Enter purpose" /></label><Field label="Required Date"><input className={inputClass} type="date" min={todayInput()} value={form.requiredDate} onChange={(event) => updateForm("requiredDate", event.target.value)} required /></Field></form></Modal>
    <Modal open={Boolean(details)} onClose={() => setDetails(null)} title="Stock Request Details" subtitle={details?.requestReference || "Request details"} width="max-w-2xl"><div className="grid gap-3 sm:grid-cols-2"><Detail label="Requester" value={details?.requester?.name} /><Detail label="Department" value={details?.department?.name} /><Detail label="Product" value={details?.product?.name} /><Detail label="Requested Quantity" value={number(details?.requestedQuantity)} /><Detail label="Available" value={number(details?.availableQuantity)} /><Detail label="Required Date" value={dateValue(details?.requiredDate)} /><Detail label="Status" value={<StatusBadge status={details?.status} />} /><Detail label="Approver" value={details?.approver?.name} /><div className="sm:col-span-2"><Detail label="Purpose" value={details?.notes} /></div></div></Modal>
    <Modal open={issue.open} onClose={() => setIssue({ open: false, row: null, warehouse: "", location: "" })} title="Issue Approved Stock" subtitle={`Select the source position for ${issue.row?.requestReference || "this request"}.`} width="max-w-xl" footer={<div className="flex justify-end gap-2"><button type="button" className={`${buttonClass} border-gray-200 bg-white`} onClick={() => setIssue({ open: false, row: null, warehouse: "", location: "" })}>Cancel</button><button type="button" className={`${buttonClass} border-indigo-600 bg-indigo-600 text-white`} disabled={!issue.warehouse || actionKey} onClick={() => perform(issue.row, "issue", { warehouse: issue.warehouse, location: issue.location || undefined })}>Issue Stock</button></div>}><div className="grid gap-4"><Field label="Warehouse"><select className={inputClass} value={issue.warehouse} onChange={(event) => warehouseChanged(event.target.value)}><option value="">Select Warehouse</option>{warehouses.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select></Field><Field label="Location / Bin / Shelf (Optional)"><select className={inputClass} value={issue.location} onChange={(event) => setIssue((previous) => ({ ...previous, location: event.target.value }))}><option value="">Any sufficient location</option>{locations.map((item) => <option key={item._id} value={item._id}>{item.name} ({item.code})</option>)}</select></Field></div></Modal>
  </InventoryPageShell>
}

function RequestTable({ kind, rows, loading, columns, canManage, canApprove, canIssue, actionKey, onView, onEdit, onPerform, onIssue, pendingCount, pagination, setPage }) {
  const pending = kind === "pending"
  return <section className={`${pending ? "mb-5" : ""} overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-[0_14px_40px_-32px_rgba(15,23,42,.5)]`}>{pending ? <header className="flex items-center justify-between border-b border-gray-200 px-4 py-3"><div><h2 className="text-sm font-black text-gray-950">Pending Stock Requests</h2><p className="mt-1 text-xs font-medium text-gray-500">Submitted requests waiting for approval on this page.</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-700">{pendingCount} pending</span></header> : null}<div className="overflow-x-auto"><table className={`w-full ${pending ? "min-w-[1050px]" : "min-w-[1250px]"} text-left`}><thead className="border-b border-gray-200 bg-gray-50/90 text-[11px] font-black uppercase tracking-wide text-gray-500"><tr>{pending ? <>{["Request No.", "Requester", "Department", "Product", "Quantity", "Required Date", "Status"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</> : <>{columns.date ? <th className="px-4 py-3">Date</th> : null}<th className="px-4 py-3">Request No.</th>{columns.requester ? <th className="px-4 py-3">Requester</th> : null}{columns.department ? <th className="px-4 py-3">Department</th> : null}<th className="px-4 py-3">Product</th><th className="px-4 py-3">Requested Qty</th>{columns.available ? <th className="px-4 py-3">Available</th> : null}{columns.requiredDate ? <th className="px-4 py-3">Required Date</th> : null}<th className="px-4 py-3">Status</th>{columns.approver ? <th className="px-4 py-3">Approver</th> : null}</>}<th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-gray-100">{loading ? <LoadingRows cells={pending ? 8 : 11} /> : rows.length ? rows.map((row) => pending ? <PendingRow key={row._id} row={row} canManage={canManage} canApprove={canApprove} actionKey={actionKey} onView={onView} onEdit={onEdit} onPerform={onPerform} /> : <HistoryRow key={row._id} row={row} columns={columns} canIssue={canIssue} onView={onView} onIssue={onIssue} />) : <EmptyRow cells={pending ? 8 : 11} message={pending ? "No pending stock requests match the current filters." : "No stock request history matches the current filters."} />}</tbody></table></div><Pagination value={pagination} onChange={setPage} /></section>
}
function PendingRow({ row, canManage, canApprove, actionKey, onView, onEdit, onPerform }) { return <tr className="hover:bg-indigo-50/30"><td className="px-4 py-4 text-sm font-bold text-gray-900">{row.requestReference}</td><td className="px-4 py-4 text-sm font-medium text-gray-800">{row.requester?.name || "—"}</td><td className="px-4 py-4 text-sm font-medium text-gray-800">{row.department?.name || "—"}</td><td className="px-4 py-4 text-sm font-medium text-gray-800">{row.product?.name || "—"}</td><td className="px-4 py-4 text-sm font-bold text-gray-900">{number(row.requestedQuantity)}</td><td className="px-4 py-4 text-sm font-medium text-gray-800">{dateValue(row.requiredDate)}</td><td className="px-4 py-4"><StatusBadge status={row.status} /></td><td className="px-4 py-3"><div className="flex justify-end gap-1"><ActionIcon label="View" onClick={() => onView(row)}><FiEye /></ActionIcon>{canManage ? <ActionIcon label="Edit" onClick={() => onEdit(row)}><FiEdit2 /></ActionIcon> : null}{canApprove ? <button type="button" className="inline-flex items-center gap-2 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white" disabled={actionKey} onClick={() => onPerform(row, "approve")}><FiCheckCircle /> Status</button> : null}{canApprove ? <ActionIcon label="Reject" danger onClick={() => onPerform(row, "reject", { reason: "Rejected during inventory review" })}><FiX /></ActionIcon> : null}</div></td></tr> }
function HistoryRow({ row, columns, canIssue, onView, onIssue }) { return <tr className="hover:bg-indigo-50/30">{columns.date ? <td className="px-4 py-4 text-sm font-medium text-gray-800">{dateValue(row.requestDate)}</td> : null}<td className="px-4 py-4 text-sm font-bold text-gray-900">{row.requestReference}</td>{columns.requester ? <td className="px-4 py-4 text-sm font-medium text-gray-800">{row.requester?.name || "—"}</td> : null}{columns.department ? <td className="px-4 py-4 text-sm font-medium text-gray-800">{row.department?.name || "—"}</td> : null}<td className="px-4 py-4 text-sm font-medium text-gray-800">{row.product?.name || "—"}</td><td className="px-4 py-4 text-sm font-bold text-gray-900">{number(row.requestedQuantity)}</td>{columns.available ? <td className="px-4 py-4 text-sm font-medium text-gray-800">{number(row.availableQuantity)}</td> : null}{columns.requiredDate ? <td className="px-4 py-4 text-sm font-medium text-gray-800">{dateValue(row.requiredDate)}</td> : null}<td className="px-4 py-4"><StatusBadge status={row.status} /></td>{columns.approver ? <td className="px-4 py-4 text-sm font-medium text-gray-800">{row.approver?.name || "—"}</td> : null}<td className="px-4 py-3"><div className="flex justify-end gap-1"><ActionIcon label="View" onClick={() => onView(row)}><FiEye /></ActionIcon>{clean(row.status).toLowerCase() === "approved" && canIssue ? <button type="button" className="rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white" onClick={() => onIssue(row)}>Issue</button> : null}</div></td></tr> }
function ActionIcon({ label, onClick, danger = false, children }) { return <button type="button" title={label} aria-label={label} onClick={onClick} className={`rounded-lg p-2 transition ${danger ? "text-rose-500 hover:bg-rose-50" : "text-gray-400 hover:bg-gray-100 hover:text-indigo-600"}`}>{children}</button> }
function LoadingRows({ cells }) { return Array.from({ length: 2 }, (_, index) => <tr key={index} className="animate-pulse">{Array.from({ length: cells }, (__, cell) => <td key={cell} className="px-4 py-5"><div className="h-4 w-20 rounded bg-gray-200" /></td>)}</tr>) }
function EmptyRow({ cells, message }) { return <tr><td colSpan={cells} className="px-5 py-14 text-center text-sm font-semibold text-gray-500">{message}</td></tr> }
